"""Build original, static rural scenery in runtime coordinates, then export OBJ."""
from collections import Counter
from pathlib import Path
import json
import math
import random

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "project/Resources/title"
GROUND_Y = -0.235
ATLAS_COLUMNS, ATLAS_ROWS = 3, 2
ATLAS_INSET = 0.025
GRASS, DIRT, FOLIAGE, RICE, WOOD, WATER = range(6)
MAX_TRIANGLES = 12000
# Staged farm: 5x4 cells, pitch1.30, center(0,6), with a one-unit scenery setback.
FARM_EXCLUSION = (-4.25, 4.25, 2.4, 9.6)
TREE_POSITIONS = ((-19,22),(-11,30),(-25,38),(-3,36),(18,24),(27,32),(8,39),(24,43))
BUSH_POSITIONS = ((-16,17),(-7,24),(22,18),(29,39))


def ground_height(x, z):
    # Keep the farm and entire road flat; only the distant meadow rolls gently.
    distance = max(abs(x)-18, z-32, 0)
    t = min(distance/18, 1)
    weight = t*t*(3-2*t)
    return GROUND_Y + weight*(.45+.16*math.sin(x*.12)+.12*math.cos(z*.11))


class Mesh:
    def __init__(self):
        self.triangles = []

    def triangle(self, points, uv, material, section):
        assert 0 <= material < ATLAS_COLUMNS * ATLAS_ROWS
        u = tuple(points[1][j] - points[0][j] for j in range(3))
        v = tuple(points[2][j] - points[0][j] for j in range(3))
        n = (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
        length = math.sqrt(sum(x*x for x in n))
        assert length > 1e-7 and all(math.isfinite(x) for p in points for x in p)
        self.triangles.append((points, uv, tuple(x/length for x in n), material, section))

    def quad(self, points, material, section, uv=((0,0), (0,1), (1,1), (1,0))):
        for indexes in ((0,1,2), (0,2,3)):
            self.triangle(tuple(points[i] for i in indexes), tuple(uv[i] for i in indexes), material, section)

    def rectangle(self, x0, x1, z0, z1, y, material, section, tile=2):
        nx, nz = math.ceil((x1-x0)/tile), math.ceil((z1-z0)/tile)
        for ix in range(nx):
            for iz in range(nz):
                a, b = x0+(x1-x0)*ix/nx, x0+(x1-x0)*(ix+1)/nx
                c, d = z0+(z1-z0)*iz/nz, z0+(z1-z0)*(iz+1)/nz
                self.quad(((a,y,c),(a,y,d),(b,y,d),(b,y,c)), material, section)

    def box(self, x, y, z, rx, ry, rz, material, section):
        a,b,c,d = (x-rx,y+ry,z-rz),(x-rx,y+ry,z+rz),(x+rx,y+ry,z+rz),(x+rx,y+ry,z-rz)
        e,f,g,h = (x-rx,y-ry,z-rz),(x-rx,y-ry,z+rz),(x+rx,y-ry,z+rz),(x+rx,y-ry,z-rz)
        for points in ((a,b,c,d),(b,f,g,c),(d,h,e,a),(a,e,f,b),(c,g,h,d),(e,h,g,f)):
            self.quad(points, material, section)

    def crown(self, x, y, z, rx, ry, rz):
        segments = 10
        rings = ((-.85,.35),(-.48,.84),(0,1),(.52,.78),(.88,.32))
        def point(h, r, i):
            angle = math.tau*i/segments
            return (x+rx*r*math.cos(angle),y+ry*h,z+rz*r*math.sin(angle))
        for ring, ((ha,ra),(hb,rb)) in enumerate(zip(rings,rings[1:])):
            for i in range(segments):
                uv = ((i/segments,1-ring/4),(i/segments,1-(ring+1)/4),
                      ((i+1)/segments,1-(ring+1)/4),((i+1)/segments,1-ring/4))
                self.quad((point(ha,ra,i),point(hb,rb,i),point(hb,rb,i+1),point(ha,ra,i+1)),FOLIAGE,"forest",uv)
        for i in range(segments):
            self.triangle(((x,y-ry,z),point(*rings[0],i),point(*rings[0],i+1)),((.5,.5),(0,1),(1,1)),FOLIAGE,"forest")
            self.triangle(((x,y+ry,z),point(*rings[-1],i+1),point(*rings[-1],i)),((.5,.5),(1,1),(0,1)),FOLIAGE,"forest")

    def save(self):
        assert len(self.triangles) <= MAX_TRIANGLES
        lines = ["# Generated by tools/title/generate_title_landscape.py; original geometry.","o RuralTitleLandscape","s off"]
        for points, uv, normal, material, _ in self.triangles:
            # Model loader reflects X and flips winding/UV: export its inverse here.
            for index in (0,2,1):
                p = points[index]
                lines.append(f"v {-p[0]:.7f} {p[1]:.7f} {p[2]:.7f}")
                u,v = uv[index]
                u = (material%ATLAS_COLUMNS+ATLAS_INSET+u*(1-2*ATLAS_INSET))/ATLAS_COLUMNS
                v = (material//ATLAS_COLUMNS+ATLAS_INSET+v*(1-2*ATLAS_INSET))/ATLAS_ROWS
                lines.append(f"vt {u:.7f} {1-v:.7f}")
            lines.append(f"vn {-normal[0]:.7f} {normal[1]:.7f} {normal[2]:.7f}")
        for i in range(len(self.triangles)):
            lines.append("f " + " ".join(f"{i*3+j+1}/{i*3+j+1}/{i+1}" for j in range(3)))
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT/"countryside.obj").write_text("\n".join(lines)+"\n",encoding="ascii")
        metadata = {"triangles":len(self.triangles),"sections":dict(Counter(t[4] for t in self.triangles)),
                    "materials":sorted(set(t[3] for t in self.triangles)),"groundY":GROUND_Y,
                    "atlasColumns":ATLAS_COLUMNS,"atlasRows":ATLAS_ROWS,"atlasInset":ATLAS_INSET}
        (OUT/"countryside_mesh.json").write_text(json.dumps(metadata,indent=2)+"\n",encoding="ascii")
        print(json.dumps(metadata))


def build():
    mesh = Mesh()
    for x in range(-50,50,5):
        for z in range(-74,86,5):
            points = tuple((a,ground_height(a,b),b) for a,b in ((x,z),(x,z+5),(x+5,z+5),(x+5,z)))
            mesh.quad(points,GRASS,"ground")
    road = ((6,-16),(6,-3),(6.5,4),(7,11),(8.5,20),(12,32))
    road_y, half_width, median = GROUND_Y+.02, .95, .18
    for (x0,z0),(x1,z1) in zip(road,road[1:]):
        count = math.ceil((z1-z0)/2)
        for step in range(count):
            a,b = step/count,(step+1)/count
            xa,za = x0+(x1-x0)*a,z0+(z1-z0)*a
            xb,zb = x0+(x1-x0)*b,z0+(z1-z0)*b
            mesh.quad(((xa-half_width,road_y,za),(xb-half_width,road_y,zb),
                       (xb+half_width,road_y,zb),(xa+half_width,road_y,za)),DIRT,"road")
            mesh.quad(((xa-median,road_y+.008,za),(xb-median,road_y+.008,zb),
                       (xb+median,road_y+.008,zb),(xa+median,road_y+.008,za)),GRASS,"road_median")
            for side in (-1,1):
                edge = side*(half_width+.14)
                mesh.quad(((xa+edge-.12,road_y+.004,za),(xb+edge-.12,road_y+.004,zb),
                           (xb+edge+.12,road_y+.004,zb),(xa+edge+.12,road_y+.004,za)),GRASS,"road_verge")
        if z0 >= 3:
            mesh.box(x0+half_width+.35,GROUND_Y+.25,z0,.035,.28,.035,WOOD,"road_posts")
    rng = random.Random(20260930)
    for x,z in TREE_POSITIONS:
        y = ground_height(x,z)
        height = rng.uniform(1.8,3.6)
        mesh.box(x,y+height*.45,z,.12,height*.45,.12,WOOD,"forest_trunks")
        mesh.crown(x,y+height*.80,z,rng.uniform(1.6,2.1),height*.65,1.35)
        mesh.crown(x+rng.uniform(-.5,.5),y+height*.65,z-.2,1.2,height*.43,.9)
    for x,z in BUSH_POSITIONS:
        mesh.crown(x,ground_height(x,z)+.55,z,.85,.55,.65)
    return mesh


if __name__ == "__main__":
    build().save()
