#include "InputKey.h"

#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>

int ToDirectInputKey(InputKey key) noexcept
{
	switch (key) {
	case InputKey::A:
		return DIK_A;
	case InputKey::B:
		return DIK_B;
	case InputKey::C:
		return DIK_C;
	case InputKey::D:
		return DIK_D;
	case InputKey::E:
		return DIK_E;
	case InputKey::F:
		return DIK_F;
	case InputKey::G:
		return DIK_G;
	case InputKey::H:
		return DIK_H;
	case InputKey::I:
		return DIK_I;
	case InputKey::J:
		return DIK_J;
	case InputKey::K:
		return DIK_K;
	case InputKey::L:
		return DIK_L;
	case InputKey::M:
		return DIK_M;
	case InputKey::N:
		return DIK_N;
	case InputKey::O:
		return DIK_O;
	case InputKey::P:
		return DIK_P;
	case InputKey::Q:
		return DIK_Q;
	case InputKey::R:
		return DIK_R;
	case InputKey::S:
		return DIK_S;
	case InputKey::T:
		return DIK_T;
	case InputKey::U:
		return DIK_U;
	case InputKey::V:
		return DIK_V;
	case InputKey::W:
		return DIK_W;
	case InputKey::X:
		return DIK_X;
	case InputKey::Y:
		return DIK_Y;
	case InputKey::Z:
		return DIK_Z;
	case InputKey::Num0:
		return DIK_0;
	case InputKey::Num1:
		return DIK_1;
	case InputKey::Num2:
		return DIK_2;
	case InputKey::Num3:
		return DIK_3;
	case InputKey::Num4:
		return DIK_4;
	case InputKey::Num5:
		return DIK_5;
	case InputKey::Num6:
		return DIK_6;
	case InputKey::Num7:
		return DIK_7;
	case InputKey::Num8:
		return DIK_8;
	case InputKey::Num9:
		return DIK_9;
	case InputKey::Escape:
		return DIK_ESCAPE;
	case InputKey::Space:
		return DIK_SPACE;
	case InputKey::Enter:
		return DIK_RETURN;
	case InputKey::Tab:
		return DIK_TAB;
	case InputKey::LeftShift:
		return DIK_LSHIFT;
	case InputKey::RightShift:
		return DIK_RSHIFT;
	case InputKey::Comma:
		return DIK_COMMA;
	case InputKey::Period:
		return DIK_PERIOD;
	case InputKey::Unknown:
	default:
		return -1;
	}
}
