#include "editor/EditorLocalization.h"

#include <array>

namespace {
struct LocalizedText {
	std::string_view english;
	std::u8string_view japanese;
};

constexpr std::array kJapaneseText = {
	LocalizedText{ "Farm Editor", u8"畑エディター" },
	LocalizedText{ "Display", u8"表示" },
	LocalizedText{ "Window", u8"ウィンドウ" },
	LocalizedText{ "Font", u8"フォント" },
	LocalizedText{ "Language", u8"表示言語" },
	LocalizedText{ "Japanese", u8"日本語" },
	LocalizedText{ "English", u8"English" },
	LocalizedText{ "Farm Map", u8"畑マップ" },
	LocalizedText{ "Farm Hierarchy", u8"畑階層" },
	LocalizedText{ "Farm Inspector", u8"畑インスペクター" },
	LocalizedText{ "Playtest", u8"プレイテスト" },
	LocalizedText{ "CLEARED", u8"クリア済み" },
	LocalizedText{ "Input Locked", u8"入力ロック" },
	LocalizedText{ "Input Enabled", u8"入力有効" },
	LocalizedText{ "Inventory: %d crop(s)", u8"所持作物: %d個" },
	LocalizedText{ "Sale value: %dG", u8"販売予定: %dG" },
	LocalizedText{ "Unit price: %dG", u8"単価: %dG" },
	LocalizedText{ "Crop", u8"作物" },
	LocalizedText{ "Seeds", u8"種" },
	LocalizedText{ "Harvested", u8"収穫" },
	LocalizedText{ "Value", u8"評価額" },
	LocalizedText{ "F: Sell all / V: Sell selected crop", u8"F: 全作物を売却 / V: 選択中の作物だけ売却" },
	LocalizedText{ "Goal: %dG left / %d crop(s) needed", u8"目標まで: %dG / あと%d個" },
	LocalizedText{ "Goal cannot be calculated", u8"目標を計算できません" },
	LocalizedText{ "Last Action", u8"直前の結果" },
	LocalizedText{ "Video Verification", u8"動画確認項目" },
	LocalizedText{ "Observed", u8"確認済み" },
	LocalizedText{ "Not observed", u8"未確認" },
	LocalizedText{ "Empty Sale", u8"空販売" },
	LocalizedText{ "Harvest", u8"収穫" },
	LocalizedText{ "Sold", u8"販売" },
	LocalizedText{ "Input Lock", u8"クリア後入力" },
	LocalizedText{ "Restart", u8"リスタート" },
	LocalizedText{ "Restart Farm", u8"畑を最初からやり直す" },
	LocalizedText{ "Farm History", u8"操作履歴" },
	LocalizedText{ "CG5 Demo", u8"CG5デモ" },
	LocalizedText{ "Console", u8"コンソール" },
	LocalizedText{ "Editor Settings", u8"エディター設定" },
	LocalizedText{ "Scene Visibility", u8"シーン表示" },
	LocalizedText{ "Fullscreen PostEffect", u8"フルスクリーンPostEffect" },
	LocalizedText{ "PostEffect Workspace###Fullscreen PostEffect", u8"PostEffectワークスペース###Fullscreen PostEffect" },
	LocalizedText{ "Pipeline Status", u8"パイプライン状態" },
	LocalizedText{ "Mode", u8"モード" },
	LocalizedText{ "Single", u8"単体" },
	LocalizedText{ "Chain", u8"チェーン" },
	LocalizedText{ "Active Effect", u8"適用中のEffect" },
	LocalizedText{ "Multiple Passes", u8"複数Pass" },
	LocalizedText{ "CG5 Quick Check", u8"CG5クイック確認" },
	LocalizedText{ "Scored Effects", u8"加点対象Effect" },
	LocalizedText{ "Presets disable Chain Mode for a stable comparison.", u8"比較を安定させるためPreset適用時はChain ModeをOFFにします。" },
	LocalizedText{ "Gaussian Filter (+5)", u8"Gaussian Filter (+5)" },
	LocalizedText{ "Gaussian Sigma", u8"Gaussian Sigma" },
	LocalizedText{ "Effect Mode", u8"Effectモード" },
	LocalizedText{ "PostEffect Chain Mode", u8"PostEffect Chain Mode" },
	LocalizedText{ "Fullscreen Effect", u8"単体Effect" },
	LocalizedText{ "Enabled Passes", u8"有効Pass数" },
	LocalizedText{ "Parameter Target", u8"パラメーター対象" },
	LocalizedText{ "Selected Effect Parameters", u8"選択Effectのパラメーター" },
	LocalizedText{ "This effect has no adjustable parameters.", u8"このEffectには調整項目がありません。" },
	LocalizedText{ "Kernel size is fixed by the selected effect.", u8"Kernelサイズは選択したEffectで固定されます。" },
	LocalizedText{ "No noise textures are loaded.", u8"Noise Textureが読み込まれていません。" },
	LocalizedText{ "Pipeline Details", u8"パイプライン詳細" },
	LocalizedText{ "Chain Mode", u8"Chain Mode" },
	LocalizedText{ "Reset All PostEffect Parameters", u8"PostEffectパラメーターをすべて初期化" },
	LocalizedText{ "Farm Map###FarmMap", u8"畑マップ###FarmMap" },
	LocalizedText{ "Farm Hierarchy###FarmHierarchy", u8"畑階層###FarmHierarchy" },
	LocalizedText{ "Game Viewport###GameViewport", u8"ゲームビュー###GameViewport" },
	LocalizedText{ "Farm Inspector###FarmInspector", u8"畑インスペクター###FarmInspector" },
	LocalizedText{ "Farm History###FarmHistory", u8"操作履歴###FarmHistory" },
	LocalizedText{ "CG5 Demo###CG5Demo", u8"CG5デモ###CG5Demo" },
	LocalizedText{ "Console###Console", u8"コンソール###Console" },
	LocalizedText{ "Farm Toolbar###FarmToolbar", u8"畑ツールバー###FarmToolbar" },
	LocalizedText{ "Editor Settings###EditorSettings", u8"エディター設定###EditorSettings" },
	LocalizedText{ "Scene Visibility###Visibility & Cull", u8"シーン表示###Visibility & Cull" },
	LocalizedText{ "Visible", u8"表示中" },
	LocalizedText{ "Debug visualizations are visible.", u8"デバッグ表示が有効です。" },
	LocalizedText{ "Debug visualizations are hidden.", u8"デバッグ表示は非表示です。" },
	LocalizedText{ "Quick Presets", u8"クイックプリセット" },
	LocalizedText{ "Show All###VisibilityShowAll", u8"すべて表示###VisibilityShowAll" },
	LocalizedText{ "Hide Debug###VisibilityHideDebug", u8"デバッグ非表示###VisibilityHideDebug" },
	LocalizedText{ "Farm Editing###VisibilityFarmEditing", u8"畑編集###VisibilityFarmEditing" },
	LocalizedText{ "Clean Capture###VisibilityCleanCapture", u8"撮影用###VisibilityCleanCapture" },
	LocalizedText{ "Reset###VisibilityReset", u8"初期状態に戻す###VisibilityReset" },
	LocalizedText{ "Show every Scene object and debug visualization.", u8"すべてのScene Objectとデバッグ表示を有効にします。" },
	LocalizedText{ "Keep Scene objects visible and hide only debug helpers.", u8"Scene Objectを維持し、デバッグ補助表示だけを隠します。" },
	LocalizedText{ "Show the Farm, Level objects, and effects without test objects.", u8"テスト用Objectを隠し、畑・Level Object・エフェクトを表示します。" },
	LocalizedText{ "Show only the Farm, HUD, and effect particles for recording.", u8"録画用に畑・HUD・エフェクトParticleだけを表示します。" },
	LocalizedText{ "Editing", u8"編集対象" },
	LocalizedText{ "Edit Focus", u8"編集対象" },
	LocalizedText{ "Scene Objects", u8"シーンオブジェクト" },
	LocalizedText{ "Sphere", u8"Sphere" },
	LocalizedText{ "Plane", u8"Plane" },
	LocalizedText{ "Sprite (2D)", u8"Sprite (2D)" },
	LocalizedText{ "Particles", u8"Particle" },
	LocalizedText{ "Animated Model", u8"Animation Model" },
	LocalizedText{ "Level Objects", u8"Level Object" },
	LocalizedText{ "Farm Visualization", u8"畑表示" },
	LocalizedText{ "Farm grid and tile selection stay visible.", u8"畑Gridと選択枠は常に表示されます。" },
	LocalizedText{ "Debug Gizmos", u8"デバッグGizmo" },
	LocalizedText{ "Skeleton Debug", u8"Skeleton Debug" },
	LocalizedText{ "Level Gizmos", u8"Level Gizmo" },
	LocalizedText{ "Collision Gizmos", u8"Collision Gizmo" },
	LocalizedText{ "Level object bounds, routes, cameras, lights, and trigger helpers.", u8"Level Objectの境界、経路、Camera、Light、Trigger補助表示です。" },
	LocalizedText{ "Runtime collider bounds. This includes the large cyan debug box.", u8"実行時Colliderの範囲です。大きな水色のDebug Boxも含みます。" },
	LocalizedText{ "Advanced Rendering", u8"詳細描画設定" },
	LocalizedText{ "Cull Mode", u8"Cull Mode" },
	LocalizedText{ "Editor Appearance", u8"エディター表示設定" },
	LocalizedText{ "UI Scale", u8"UI倍率" },
	LocalizedText{ "Theme", u8"テーマ" },
	LocalizedText{ "Reset Window Layout", u8"ウィンドウ配置を初期化" },
	LocalizedText{ "Saved to %s", u8"設定保存先: %s" },
	LocalizedText{ "New", u8"新規作成" },
	LocalizedText{ "Create an empty Farm document", u8"空の畑データを新規作成します" },
	LocalizedText{ "Saves...", u8"セーブ一覧..." },
	LocalizedText{ "View, search, load, or rename saved Farm documents", u8"保存済みの畑データを検索、読込、名前変更します" },
	LocalizedText{ "Save", u8"上書き保存" },
	LocalizedText{ "Ctrl+S: Save changes", u8"Ctrl+S: 変更を上書き保存" },
	LocalizedText{ "Farm document is already saved", u8"変更は保存済みです" },
	LocalizedText{ "Name and save this Farm document", u8"この畑データに名前を付けて保存します" },
	LocalizedText{ "Save As...", u8"名前を付けて保存..." },
	LocalizedText{ "Save a copy with a new name (Japanese is supported)", u8"新しい名前でコピーを保存します（日本語対応）" },
	LocalizedText{ "NEW", u8"新規" },
	LocalizedText{ "UNSAVED", u8"未保存" },
	LocalizedText{ "SAVED", u8"保存済み" },
	LocalizedText{ "ERROR", u8"エラー" },
	LocalizedText{ "Clear", u8"クリア" },
	LocalizedText{ "Info", u8"情報" },
	LocalizedText{ "Warning", u8"警告" },
	LocalizedText{ "Error", u8"エラー" },
	LocalizedText{ "Search logs...", u8"ログを検索..." },
	LocalizedText{ "Auto-scroll", u8"自動スクロール" },
	LocalizedText{ "Time", u8"時刻" },
	LocalizedText{ "Level", u8"種類" },
	LocalizedText{ "Message", u8"メッセージ" },
	LocalizedText{ "Selected log", u8"選択中のログ" },
	LocalizedText{ "No logs match the current filters.", u8"現在の条件に一致するログはありません。" },
	LocalizedText{ "Resume simulation", u8"シミュレーションを再開" },
	LocalizedText{ "Pause simulation", u8"シミュレーションを一時停止" },
	LocalizedText{ "Advance one simulation step", u8"シミュレーションを1ステップ進める" },
	LocalizedText{ "PLAYING", u8"実行中" },
	LocalizedText{ "PAUSED", u8"一時停止" },
	LocalizedText{ "Simulation Tick", u8"シミュレーションTick" },
	LocalizedText{ "Required Effect", u8"必須エフェクト" },
	LocalizedText{ "READY", u8"準備完了" },
	LocalizedText{ "NOT ACTIVE", u8"未適用" },
	LocalizedText{ "Compare the same Farm scene before and after Grayscale.", u8"同じFarm SceneでGrayscale適用前後を比較します。" },
	LocalizedText{ "Original Color", u8"元のカラー" },
	LocalizedText{ "Required Grayscale", u8"必須 Grayscale" },
	LocalizedText{ "Current Effect", u8"現在のEffect" },
	LocalizedText{ "Bonus Effect", u8"加点エフェクト" },
	LocalizedText{ "Highlight Farm depth boundaries for the scored bonus demo.", u8"畑の深度境界を強調し、加点対象のOutlineを確認します。" },
	LocalizedText{ "Depth-Based Outline", u8"Depth-Based Outline" },
	LocalizedText{ "Depth Threshold", u8"深度しきい値" },
	LocalizedText{ "Outline Intensity", u8"Outline強度" },
	LocalizedText{ "Outline Thickness", u8"Outline太さ" },
	LocalizedText{ "Linearize Depth", u8"Depthを線形化" },
	LocalizedText{ "Hoe", u8"耕す" },
	LocalizedText{ "Water", u8"水やり" },
	LocalizedText{ "Seed", u8"植える" },
	LocalizedText{ "Harvest", u8"収穫" },
	LocalizedText{ "Undo", u8"元に戻す" },
	LocalizedText{ "Redo", u8"やり直す" },
	LocalizedText{ "No Farm edit to undo", u8"元に戻せる畑操作はありません" },
	LocalizedText{ "No Farm edit to redo", u8"やり直せる畑操作はありません" },
	LocalizedText{ "No tile selected", u8"畑マスが選択されていません" },
	LocalizedText{ "Tile #%d", u8"畑マス #%d" },
	LocalizedText{ "Reset Layout", u8"レイアウト初期化" },
	LocalizedText{ "Discard unsaved Farm edits?###FarmDiscardChanges", u8"未保存の畑編集を破棄しますか？###FarmDiscardChanges" },
	LocalizedText{ "The current Farm has unsaved changes.", u8"現在の畑データには未保存の変更があります。" },
	LocalizedText{ "Continuing will discard those edits.", u8"続行すると変更内容は失われます。" },
	LocalizedText{ "Cancel", u8"キャンセル" },
	LocalizedText{ "Discard", u8"破棄して続行" },
	LocalizedText{ "Save Farm As###FarmSaveAs", u8"名前を付けて保存###FarmSaveAs" },
	LocalizedText{ "Farm name", u8"セーブ名" },
	LocalizedText{ "Japanese names are stored as UTF-8. The filename remains safe and internal.", u8"日本語名はUTF-8で保存され、内部ファイル名には使用されません。" },
	LocalizedText{ "Farm Saves###FarmSaves", u8"セーブデータ###FarmSaves" },
	LocalizedText{ "Saved Farms (%zu)", u8"セーブデータ (%zu件)" },
	LocalizedText{ "Select a save to load or rename it", u8"読込または名前変更するデータを選択してください" },
	LocalizedText{ "Search by name...", u8"名前で検索..." },
	LocalizedText{ "Name", u8"名前" },
	LocalizedText{ "Saved", u8"保存日時" },
	LocalizedText{ "[Open] ", u8"[使用中] " },
	LocalizedText{ "Selected: %s%s", u8"選択中: %s%s" },
	LocalizedText{ " (currently open)", u8"（現在使用中）" },
	LocalizedText{ "No Farm saves yet. Use Save As to create one.", u8"セーブデータがありません。「名前を付けて保存」で作成してください。" },
	LocalizedText{ "Close", u8"閉じる" },
	LocalizedText{ "Load Selected", u8"選択データを読み込む" },
	LocalizedText{ "Rename...", u8"名前変更..." },
	LocalizedText{ "Rename selected save", u8"選択したセーブの名前変更" },
	LocalizedText{ "The internal save ID and file path will not change.", u8"内部IDと保存ファイルの場所は変更されません。" },
	LocalizedText{ "Cancel Rename", u8"名前変更を中止" },
	LocalizedText{ "Apply Rename", u8"名前を変更" },
	LocalizedText{ "Delete...", u8"削除..." },
	LocalizedText{ "Delete selected save", u8"選択したセーブを削除" },
	LocalizedText{ "Delete Farm Save###FarmDeleteSave", u8"セーブデータを削除###FarmDeleteSave" },
	LocalizedText{ "Delete \"%s\"?", u8"「%s」を削除しますか？" },
	LocalizedText{ "This operation cannot be undone.", u8"この操作は元に戻せません。" },
	LocalizedText{ "The current Farm will remain open as an unsaved document.", u8"現在の畑は未保存データとして開いたまま残ります。" },
	LocalizedText{ "Delete Save", u8"セーブを削除" },
	LocalizedText{ "Farm data is unavailable.", u8"畑データを利用できません。" },
	LocalizedText{ "Farm Grid  %d x %d", u8"畑グリッド  %d x %d" },
	LocalizedText{ "Click a tile to select it", u8"畑マスをクリックして選択" },
	LocalizedText{ "Empty", u8"未耕作" },
	LocalizedText{ "Tilled", u8"耕し済み" },
	LocalizedText{ "Watered", u8"水やり済み" },
	LocalizedText{ "Planted", u8"植え付け済み" },
	LocalizedText{ "Growing", u8"成長中" },
	LocalizedText{ "Sprout", u8"芽生え" },
	LocalizedText{ "Almost Ready", u8"収穫間近" },
	LocalizedText{ "Ready", u8"収穫可能" },
	LocalizedText{ "TestCrop", u8"カブ" },
	LocalizedText{ "Carrot", u8"ニンジン" },
	LocalizedText{ "Legend", u8"凡例" },
	LocalizedText{ "Blue bar: moisture", u8"青いバー: 水分量" },
	LocalizedText{ "Green/gold bar: growth", u8"緑・金のバー: 成長度" },
	LocalizedText{ "Tile %d  (%d, %d)", u8"畑マス %d  (%d, %d)" },
	LocalizedText{ "State: %s", u8"状態: %s" },
	LocalizedText{ "Height: H%d", u8"高さ: H%d" },
	LocalizedText{ "Moisture: %.0f%%", u8"水分量: %.0f%%" },
	LocalizedText{ "Growth: %.0f%%", u8"成長度: %.0f%%" },
	LocalizedText{ "Selection", u8"選択中の畑マス" },
	LocalizedText{ "Coordinate (%d, %d)", u8"座標 (%d, %d)" },
	LocalizedText{ "Crop: %s", u8"作物: %s" },
	LocalizedText{ "Terrain", u8"地形" },
	LocalizedText{ "Height", u8"高さ" },
	LocalizedText{ "Feature: %s", u8"地形機能: %s" },
	LocalizedText{ "Canal", u8"用水路" },
	LocalizedText{ "Dry Canal", u8"未通水" },
	LocalizedText{ "Supplied", u8"通水中" },
	LocalizedText{ "Water Source", u8"水源" },
	LocalizedText{ "Irrigation Network", u8"灌漑ネットワーク" },
	LocalizedText{ "Sources %d / Supplied canals %d / Irrigation range %d", u8"水源 %d / 通水用水路 %d / 灌漑範囲 %d" },
	LocalizedText{ "Irrigation range: %s", u8"灌漑範囲: %s" },
	LocalizedText{ "In range", u8"範囲内" },
	LocalizedText{ "Out of range", u8"範囲外" },
	LocalizedText{ "Supplied by canal #%d", u8"用水路 #%d から給水" },
	LocalizedText{ "Irrigation active", u8"灌漑中" },
	LocalizedText{ "Supply strength: %.0f%%", u8"供給強度: %.0f%%" },
	LocalizedText{ "Irrigation strength: %.0f%%", u8"灌漑強度: %.0f%%" },
	LocalizedText{ "Downstream canals: %d", u8"下流の用水路: %d" },
	LocalizedText{ "Irrigation recovery: %.1f%% / sec", u8"灌漑回復: %.1f%% / 秒" },
	LocalizedText{ "Net moisture: %+.1f%% / sec", u8"水分収支: %+.1f%% / 秒" },
	LocalizedText{ "Full moisture ETA: %.1f sec", u8"満水まで: %.1f秒" },
	LocalizedText{ "Cyan line: irrigation range", u8"水色線: 灌漑範囲" },
	LocalizedText{ "Cyan line: supply strength", u8"水色線: 供給強度" },
	LocalizedText{ "Irrigation Preview", u8"灌漑プレビュー" },
	LocalizedText{ "Tile #%d: %s -> %s", u8"畑マス #%d: %s -> %s" },
	LocalizedText{ "Preview: Sources %d / Canals %d / Range %d", u8"予測: 水源 %d / 通水用水路 %d / 灌漑範囲 %d" },
	LocalizedText{ "Farm changed. Cancel and preview again.", u8"農地が変更されました。取り消して再度プレビューしてください。" },
	LocalizedText{ "Confirm Preview", u8"この変更を確定" },
	LocalizedText{ "Cancel Preview", u8"プレビューを取消" },
	LocalizedText{ "Preview Canal Removal", u8"用水路の撤去をプレビュー" },
	LocalizedText{ "Preview Canal Placement", u8"用水路の設置をプレビュー" },
	LocalizedText{ "Preview Water Source Removal", u8"水源の撤去をプレビュー" },
	LocalizedText{ "Preview Water Source Placement", u8"水源の設置をプレビュー" },
	LocalizedText{ "Preview changed tile", u8"プレビュー変更対象" },
	LocalizedText{ "Preview canal change on selected tile", u8"選択マスの用水路変更を仮計算" },
	LocalizedText{ "Preview water source change on selected tile", u8"選択マスの水源変更を仮計算" },
	LocalizedText{ "Place Canal", u8"用水路を作る" },
	LocalizedText{ "Remove Canal", u8"通常地面に戻す" },
	LocalizedText{ "Toggle canal on selected tile (N)", u8"選択マスの用水路を切り替え (N)" },
	LocalizedText{ "Next: press N to restore normal ground.", u8"次: Nで通常地面に戻す。" },
	LocalizedText{ "Place Water Source", u8"水源を作る" },
	LocalizedText{ "Remove Water Source", u8"水源を撤去する" },
	LocalizedText{ "Toggle water source on selected tile (M)", u8"選択マスの水源を切り替え (M)" },
	LocalizedText{ "Supplied from a water source. N removes this canal.", u8"水源から通水中。Nで用水路を撤去。" },
	LocalizedText{ "Dry canal: connect it to an equal or higher water source.", u8"未通水: 同じ高さか高い水源へ接続してください。" },
	LocalizedText{ "Next: connect a canal or press M to remove the source.", u8"次: 用水路を接続、またはMで水源を撤去。" },
	LocalizedText{ "Lower selected tile (Page Down)", u8"選択中の畑マスを下げます（Page Down）" },
	LocalizedText{ "Raise selected tile (Page Up)", u8"選択中の畑マスを上げます（Page Up）" },
	LocalizedText{ "Crop Status", u8"作物の状態" },
	LocalizedText{ "Stage: %s", u8"成長段階: %s" },
	LocalizedText{ "Moisture: %s", u8"水分状態: %s" },
	LocalizedText{ "Dry", u8"乾燥" },
	LocalizedText{ "Low", u8"水不足" },
	LocalizedText{ "Good", u8"適湿" },
	LocalizedText{ "Unavailable", u8"対象外" },
	LocalizedText{ "Growth profile: %s", u8"成長特性: %s" },
	LocalizedText{ "Good moisture: %.0f%% or more", u8"適湿条件: %.0f%%以上" },
	LocalizedText{ "Growth rate: %.1f%% / sec", u8"成長速度: %.1f%% / 秒" },
	LocalizedText{ "Ready ETA: %.1f sec (current rate)", u8"収穫まで: 約%.1f秒（現在速度）" },
	LocalizedText{ "Dry ETA: %.1f sec", u8"乾燥まで: 約%.1f秒" },
	LocalizedText{ "No active growth forecast", u8"成長予測の対象外です" },
	LocalizedText{ "Crop Quality", u8"作物品質" },
	LocalizedText{ "Selected Tile Preview", u8"選択マスの収穫予測" },
	LocalizedText{ "Last Harvest Result", u8"直近の収穫結果" },
	LocalizedText{ "No quality data", u8"品質データなし" },
	LocalizedText{ "Maturity", u8"成熟度" },
	LocalizedText{ "Water Balance", u8"水分バランス" },
	LocalizedText{ "Terrain Fit", u8"地形適性" },
	LocalizedText{ "Score: %d / 100  Grade %s", u8"総合: %d / 100  ランク %s" },
	LocalizedText{ "Estimated Value: %dG (Base %dG)", u8"予想売価: %dG (基本 %dG)" },
	LocalizedText{ "Growth", u8"成長度" },
	LocalizedText{ "Next: select Harvest and apply.", u8"次の操作: 「収穫」を選んで適用" },
	LocalizedText{ "Next: select Hoe to prepare this tile.", u8"次の操作: 「耕す」を選んで土を準備" },
	LocalizedText{ "Next: select Seed to plant.", u8"次の操作: 「植える」を選んで作物を植える" },
	LocalizedText{ "Next: Water this tile or plant a Seed.", u8"次の操作: 水やり、または作物を植える" },
	LocalizedText{ "Growing slowly: add Water.", u8"水分不足で成長が遅れています。水やりしてください。" },
	LocalizedText{ "Growing: wait until the crop is ready.", u8"成長中です。収穫可能になるまで待ってください。" },
	LocalizedText{ "Farm Tool", u8"農具" },
	LocalizedText{ "1  Hoe", u8"1  耕す" },
	LocalizedText{ "2  Water", u8"2  水やり" },
	LocalizedText{ "3  Seed", u8"3  植える" },
	LocalizedText{ "4  Harvest", u8"4  収穫" },
	LocalizedText{ "Action available", u8"この操作を実行できます" },
	LocalizedText{ "Already fully watered", u8"水分量はすでに最大です" },
	LocalizedText{ "Crop is not ready", u8"作物はまだ収穫できません" },
	LocalizedText{ "No valid tile", u8"有効な畑マスがありません" },
	LocalizedText{ "Tool is unavailable", u8"この農具は使用できません" },
	LocalizedText{ "Tool does not match tile state", u8"現在の畑状態ではこの農具を使えません" },
	LocalizedText{ "Apply Selected Tool", u8"選択中の農具を適用" },
	LocalizedText{ "Viewport Shortcuts", u8"ゲームビュー操作" },
	LocalizedText{ "Click: select   Shift+Click: select and apply", u8"クリック: 選択   Shift+クリック: 選択して適用" },
	LocalizedText{ "Arrows: move   Q/E: tool   Enter: apply", u8"矢印キー: 選択移動   Q/E: 農具切替   Enter: 適用" },
	LocalizedText{ "None", u8"なし" },
	LocalizedText{ "Undo %zu   Redo %zu   |   Ctrl+Z / Ctrl+Y", u8"元に戻す %zu   やり直す %zu   |   Ctrl+Z / Ctrl+Y" },
	LocalizedText{ "Next Undo: %s    |    Next Redo: %s", u8"次に戻す操作: %s    |    次にやり直す操作: %s" },
	LocalizedText{ "Hoe Tile", u8"畑を耕す" },
	LocalizedText{ "Water Tile", u8"水やり" },
	LocalizedText{ "Plant Seed", u8"作物を植える" },
	LocalizedText{ "Harvest Crop", u8"作物を収穫" },
	LocalizedText{ "Raise Tile", u8"畑マスを上げる" },
	LocalizedText{ "Lower Tile", u8"畑マスを下げる" },
	LocalizedText{ "Farm Tile Edit", u8"畑マスを編集" },
	LocalizedText{ "Scene / Farm", u8"シーン / 畑" },
	LocalizedText{ "Farm Grid", u8"畑グリッド" },
	LocalizedText{ "Farm Grid  (%d x %d)", u8"畑グリッド  (%d x %d)" },
	LocalizedText{ "Row %d", u8"行 %d" },
	LocalizedText{ "Tile %02d  [%s]", u8"畑マス %02d  [%s]" },
	LocalizedText{ "Coordinate (%d, %d)\nMoisture %.0f%%\nGrowth %.0f%%", u8"座標 (%d, %d)\n水分量 %.0f%%\n成長度 %.0f%%" },
	LocalizedText{ "Untitled Farm", u8"名称未設定の畑" },
	LocalizedText{ "New Farm document", u8"新しい畑データ" },
	LocalizedText{ "Use Save As to name this Farm document first.", u8"先に名前を付けて畑データを保存してください。" },
	LocalizedText{ "A Farm document with this name already exists.", u8"同じ名前の畑データがすでに存在します。" },
	LocalizedText{ "The selected Farm document no longer exists.", u8"選択した畑データは存在しません。" },
	LocalizedText{ "Could not read the selected Farm document.", u8"選択した畑データを読み込めませんでした。" },
	LocalizedText{ "Loaded the Farm, but could not remember it for the next launch.", u8"畑データは読み込みましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Loaded", u8"読み込みました" },
	LocalizedText{ "Farm name is unchanged", u8"畑の名前は変更されていません" },
	LocalizedText{ "Renamed", u8"名前を変更しました" },
	LocalizedText{ "Deleted", u8"削除しました" },
	LocalizedText{ "Deleted; current Farm is now unsaved", u8"削除しました。現在の畑は未保存状態です" },
	LocalizedText{ "New unsaved Farm", u8"未保存の新しい畑" },
	LocalizedText{ "Unsaved changes", u8"未保存の変更があります" },
	LocalizedText{ "Could not create or access the Farm save directory.", u8"畑の保存フォルダーを作成または参照できませんでした。" },
	LocalizedText{ "Saved the Farm, but could not remember it for the next launch.", u8"畑データは保存しましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Saved", u8"保存しました" },
	LocalizedText{ "Farm name cannot be empty.", u8"畑の名前を入力してください。" },
	LocalizedText{ "Farm name is too long.", u8"畑の名前が長すぎます。" },
	LocalizedText{ "Farm name is not valid UTF-8.", u8"畑の名前が正しいUTF-8文字列ではありません。" },
	LocalizedText{ "Farm name contains a control character.", u8"畑の名前に使用できない制御文字が含まれています。" },
	LocalizedText{ "The selected Farm document ID is invalid.", u8"選択した畑データのIDが不正です。" },
	LocalizedText{ "Could not prepare the Farm document for deletion.", u8"畑データを削除する準備ができませんでした。" },
	LocalizedText{ "Could not delete the selected Farm document.", u8"選択した畑データを削除できませんでした。" },
	LocalizedText{ "Could not refresh the Farm save list after deletion.", u8"削除後にセーブ一覧を更新できませんでした。" },
	LocalizedText{ "Could not update the Farm document catalog after deletion.", u8"削除後に畑データの管理情報を更新できませんでした。" },
};
} // namespace

const char* editor::Localize(EditorLanguage language, std::string_view englishText) noexcept {
	if (language == EditorLanguage::English) {
		return englishText.data();
	}
	for (const LocalizedText& text : kJapaneseText) {
		if (text.english == englishText) {
			return reinterpret_cast<const char*>(text.japanese.data());
		}
	}
	return englishText.data();
}

const char* editor::GetEditorLanguageStorageName(EditorLanguage language) noexcept {
	return language == EditorLanguage::English ? "English" : "Japanese";
}

EditorLanguage editor::ParseEditorLanguage(std::string_view value) noexcept {
	return value == "English" ? EditorLanguage::English : EditorLanguage::Japanese;
}
