#include "editor/EditorLocalization.h"

#include <array>

namespace {
struct LocalizedText {
	std::string_view english;
	std::u8string_view japanese;
};

constexpr std::array kJapaneseText = {
	LocalizedText{ "Day %d: %.1f / %.0f simulation seconds", u8"%d日目：%.1f / %.0f 秒（ゲーム内）" },
	LocalizedText{ "Configured speed: %.0fx (no progress while paused)", u8"設定速度：%.0f倍（停止中は進みません）" },
	LocalizedText{ "Automatic soil intake closed", u8"この畑の自動給水：切" },
	LocalizedText{ "Cultivate soil before irrigation.", u8"耕してから給水できます" },
	LocalizedText{ "Plant a crop before checking growth.", u8"種を植えてから生育を確認" },
	LocalizedText{ "Ready to harvest; no more watering needed.", u8"収穫できます：追加の水やりは不要" },
	LocalizedText{ "Low moisture: water with the watering can.", u8"水不足：じょうろで水やり" },
	LocalizedText{ "Low moisture: check soil after irrigation.", u8"水不足：給水後の水分量を確認" },
	LocalizedText{ "Excess moisture: close automatic intake.", u8"水過多：自動給水を切る" },
	LocalizedText{ "Excess moisture: avoid additional watering.", u8"水過多：追加の水やりを控える" },
	LocalizedText{ "Good moisture: monitor while growing.", u8"水分は適量：状態を見ながら育てる" },
	LocalizedText{ "Water guidance unavailable.", u8"水分状態を確認できません" },
	LocalizedText{ "Contest day %d: simulation stopped", u8"%d日目の大会：時間を停止中" },
	LocalizedText{ "Submit in inventory while stopped, or dismiss to resume. No late submissions.", u8"停止中に保管庫から提出できます。案内を閉じると再開します。当日を過ぎると提出できません。" },
	LocalizedText{ "Dismiss contest notice and resume", u8"大会案内を閉じて時間を進める" },
	LocalizedText{ "Submit reserved crop", u8"予約した１個を提出" },
	LocalizedText{ "Submit on day 10, 20 or 30. One crop is consumed; save results with the farm.", u8"提出は10・20・30日目。１個を消費し、結果は農場と一緒に保存します。" },
	LocalizedText{ "Consume one reserved crop? Submission cannot be undone.", u8"予約した１個を提出しますか？ 消費後は元に戻せません。" },
	LocalizedText{ "Confirm submission", u8"提出を確定" },
	LocalizedText{ "Contest submission results", u8"大会の提出結果" },
	LocalizedText{ "30-day contest mode", u8"３０日間の大会モード" },
	LocalizedText{ "540G trial mode", u8"５４０Ｇの体験版モード" },
	LocalizedText{ "Switch to trial mode", u8"体験版モードへ切替" },
	LocalizedText{ "Switch to contest mode", u8"大会モードへ切替" },
	LocalizedText{ "Switch rules, keep the farm, commit edit history.", u8"進行ルールを切替。農場は維持し、操作履歴を確定します。" },
	LocalizedText{ "Final contest summary", u8"３０日間の大会結果" },
	LocalizedText{ "Provisional contest rating: %s", u8"大会評価（仮）：%s" },
	LocalizedText{ "Next rating %s: %d points needed", u8"次の評価 %s まで：あと%d点" },
	LocalizedText{ "Rating uses final submitted results only; no entry or unfinished season is unrated. No prize payout.", u8"最終結果の提出済み得点だけで評価。未終了・出場なしは評価なし。賞金はありません。" },
	LocalizedText{ "Contest season in progress", u8"大会期間中の集計" },
	LocalizedText{ "Invalid contest summary", u8"大会結果を確認できません" },
	LocalizedText{ "Submitted %d / missed %d / total %d points", u8"提出 %d回 ／ 未出場 %d回 ／ 総得点 %d点" },
	LocalizedText{ "Contest upcoming", u8"開催前" },
	LocalizedText{ "Contest accepting entries", u8"受付中（当日中に提出）" },
	LocalizedText{ "Contest missed", u8"未出場（受付終了）" },
	LocalizedText{ "Day %d: not submitted", u8"%d日目：未提出" },
	LocalizedText{ "Day %d: quality %d + size %d = %d points", u8"%d日目：品質%d点 ＋ 大きさ%d点 ＝ %d点" },
	LocalizedText{ "Contest harvest period (provisional)", u8"大会の対象期間（仮ルール）" },
	LocalizedText{ "Current farm day: %d", u8"現在の農場日：%d" },
	LocalizedText{ "Contest day: %d / days remaining: %d", u8"大会日：%d／あと%d日（0は当日）" },
	LocalizedText{ "Harvest period: %d - %d (inclusive)", u8"収穫日の対象期間：%d～%d（両端を含む）" },
	LocalizedText{ "Reserved harvest day: %d (0: unknown)", u8"予約した野菜の収穫日：%d（0：不明）" },
	LocalizedText{ "Within harvest period (preview only).", u8"対象期間内です（仮判定・提出前）。" },
	LocalizedText{ "Invalid farm day.", u8"農場の日付が不正です。" },
	LocalizedText{ "No contest after day 30.", u8"30日を過ぎたため対象の大会はありません。" },
	LocalizedText{ "Harvest day unknown: reserve a newly harvested crop.", u8"収穫日不明です。新しく収穫した野菜を予約してください。" },
	LocalizedText{ "Harvest day is later than farm day.", u8"収穫日が農場の日付より未来のため対象外です。" },
	LocalizedText{ "Outside this harvest period: replace the reservation.", u8"対象期間外です。この期間に収穫した野菜へ予約を変更してください。" },
	LocalizedText{ "Period preview only. Reservation and inventory are unchanged.", u8"対象期間の仮判定のみです。予約・在庫は変更しません。" },
	LocalizedText{ "Harvest day", u8"収穫日" },
	LocalizedText{ "Harvest day unknown", u8"収穫日不明" },
	LocalizedText{ "Active harvest animations: %zu", u8"引き抜き演出中：%zu個" },
	LocalizedText{ "Sale protection", u8"売却保護" },
	LocalizedText{ "Contest reservation", u8"出品予約" },
	LocalizedText{ "Contest reservation ID: %d (0: none)", u8"出品予約ID：%d（0：なし）" },
	LocalizedText{ "Reserve one protected crop with known size. Cancel before unprotecting.", u8"保護済みでサイズ記録のある1個を予約。保護解除は予約取消後に行います。" },
	LocalizedText{ "Contest judging preview (provisional)", u8"審査プレビュー（仮ルール）" },
	LocalizedText{ "Quality: %d / 100 -> %d / %d points", u8"品質：%d / 100 → %d / %d点" },
	LocalizedText{ "Size: %.2fx -> %d / %d points", u8"大きさ：%.2fx → %d / %d点" },
	LocalizedText{ "Size range: %.2fx - %.2fx", u8"大きさの採点範囲：%.2fx ～ %.2fx" },
	LocalizedText{ "Preview total: %d / 100", u8"合計点（試算）：%d / 100" },
	LocalizedText{ "Recorded nutrient history is incomplete; stored quality is used.", u8"養分履歴が不完全な記録です。保存された品質点で試算します。" },
	LocalizedText{ "Reserve a crop in inventory first.", u8"先に保管庫で野菜を出品予約してください。" },
	LocalizedText{ "Invalid harvest record or judge rules.", u8"収穫記録または採点設定が不正です。" },
	LocalizedText{ "Preview only. Round each contribution, then sum. No submission, reward or crop consumption.", u8"各得点を四捨五入して合計する試算です。提出確定・報酬・作物の消費は行いません。" },
	LocalizedText{ "Protected crops: %d", u8"保護中の作物：%d個" },
	LocalizedText{ "Protection excludes sales; changing it commits earlier edit history.", u8"保護中は売却対象外。保護の変更時は、それ以前の操作履歴を確定します。" },
	LocalizedText{ "Harvest inventory full", u8"保管庫が満杯：売却すると収穫できます" },
	LocalizedText{ "Unsold harvest records", u8"収穫物の保管庫" },
	LocalizedText{ "Records: %zu / %zu", u8"収穫記録数：%zu / %zu" },
	LocalizedText{ "Unknown harvest details: %d crop(s)", u8"詳細不明の収穫物：%d個" },
	LocalizedText{ "Sold crops leave inventory; the last harvest result is only history.", u8"売却した作物は保管庫からなくなります。直前の収穫結果は履歴として残ります。" },
	LocalizedText{ "Recorded size", u8"収穫サイズ" },
	LocalizedText{ "Quality score", u8"品質点" },
	LocalizedText{ "Unit price", u8"単価" },
	LocalizedText{ "Growth Comparison", u8"生育比較" },
	LocalizedText{ "Pin Selected As A", u8"選択マスをAに" },
	LocalizedText{ "Pin Selected As B", u8"選択マスをBに" },
	LocalizedText{ "Start Comparison", u8"比較開始" },
	LocalizedText{ "Stop Comparison", u8"測定停止" },
	LocalizedText{ "Reset Comparison", u8"比較解除" },
	LocalizedText{ "Comparison Idle", u8"未測定" },
	LocalizedText{ "Comparison Running", u8"測定中（一時停止・プレビュー中は計時停止）" },
	LocalizedText{ "Comparison Stopped", u8"測定停止・結果保持" },
	LocalizedText{ "Comparison Completed", u8"両方が収穫可能・結果保持" },
	LocalizedText{ "Comparison Invalidated", u8"測定無効：対象マスの編集または畑の読込" },
	LocalizedText{ "Growth seconds: %.2f", u8"生育時間：%.2f 秒" },
	LocalizedText{ "Comparison: select two tiles", u8"開始条件：AとBを登録" },
	LocalizedText{ "Comparison: different tiles required", u8"開始条件：異なる２マス" },
	LocalizedText{ "Comparison: two growing crops required", u8"開始条件：両方に成長中の作物" },
	LocalizedText{ "Comparison: crop mismatch", u8"開始条件：同じ種類の作物" },
	LocalizedText{ "Comparison: height mismatch", u8"開始条件：同じ高さ" },
	LocalizedText{ "Comparison: initial growth mismatch", u8"開始条件：同じ成長度（差0.01ポイント以内）" },
	LocalizedText{ "Comparison: invalid tile data", u8"開始不可：水分・成長データが不正" },
	LocalizedText{ "Comparison Metric", u8"項目" },
	LocalizedText{ "Initial Water", u8"開始水分" },
	LocalizedText{ "Current Water", u8"現在水分" },
	LocalizedText{ "Initial Growth", u8"開始成長度" },
	LocalizedText{ "Current Growth", u8"現在成長度" },
	LocalizedText{ "Growth Gain", u8"増加ポイント" },
	LocalizedText{ "Ready At", u8"収穫可能まで" },
	LocalizedText{ "Observation includes automatic irrigation and drying; gain is percentage points.", u8"自動給水・乾燥を含む観測。増加は成長度の差分です。" },
	LocalizedText{ "Pause, plant matching crops, adjust water, pin A/B, start, then resume. Do not edit during measurement.", u8"一時停止中に同じ作物を植え、水分を調整。A/Bに登録して比較開始後に再生します。測定中の編集は避けてください。" },
	LocalizedText{ "Development Mode", u8"開発モード" },
	LocalizedText{ "Player Grounding", u8"プレイヤーの接地" },
	LocalizedText{ "Move Player To Selected Tile", u8"選択マスへプレイヤーを移動" },
	LocalizedText{ "Base Ground", u8"地面" },
	LocalizedText{ "Soil Surface", u8"畑の土" },
	LocalizedText{ "Canal Bed", u8"水路底" },
	LocalizedText{ "Canal Bank", u8"水路の岸" },
	LocalizedText{ "Surface Below", u8"足元の地形" },
	LocalizedText{ "Movement Blocked", u8"移動制限あり（段差・障害物・更新上限）" },
	LocalizedText{ "Grounded", u8"接地中" },
	LocalizedText{ "Airborne", u8"空中" },
	LocalizedText{ "Game Mode", u8"ゲームモード" },
	LocalizedText{ "Finish or cancel the preview before switching modes", u8"プレビューを確定・取消してから切り替えてください" },
	LocalizedText{ "Modes share the current Farm; switching does not reset or save it", u8"同じ畑を継続します。切替によるリセット・自動保存はありません" },
	LocalizedText{ "Farm Editor", u8"畑エディター" },
	LocalizedText{ "Display", u8"表示" },
	LocalizedText{ "Window", u8"ウィンドウ" },
	LocalizedText{ "Font", u8"フォント" },
	LocalizedText{ "Language", u8"表示言語" },
	LocalizedText{ "Japanese", u8"日本語" },
	LocalizedText{ "English", u8"English" },
	LocalizedText{ "Farm Map", u8"畑マップ" },
	LocalizedText{ "Farm Hierarchy", u8"畑階層" },
	LocalizedText{ "Farm Inspector", u8"畑インスペクター" },
	LocalizedText{ "Playtest", u8"プレイテスト" },
	LocalizedText{ "CLEARED", u8"クリア済み" },
	LocalizedText{ "Input Locked", u8"入力ロック" },
	LocalizedText{ "Input Enabled", u8"入力有効" },
	LocalizedText{ "Inventory: %d crop(s)", u8"所持作物: %d個" },
	LocalizedText{ "Sale value: %dG", u8"販売予定: %dG" },
	LocalizedText{ "Unit price: %dG", u8"単価: %dG" },
	LocalizedText{ "Crop", u8"作物" },
	LocalizedText{ "Seeds", u8"種" },
	LocalizedText{ "Harvested", u8"収穫" },
	LocalizedText{ "Value", u8"評価額" },
	LocalizedText{ "F: Sell all / V: Sell selected crop", u8"F: 全作物を売却 / V: 選択中の作物だけ売却" },
	LocalizedText{ "Goal: %dG left / %d crop(s) needed", u8"目標まで: %dG / あと%d個" },
	LocalizedText{ "Goal cannot be calculated", u8"目標を計算できません" },
	LocalizedText{ "Last Action", u8"直前の結果" },
	LocalizedText{ "Video Verification", u8"動画確認項目" },
	LocalizedText{ "Observed", u8"確認済み" },
	LocalizedText{ "Not observed", u8"未確認" },
	LocalizedText{ "Empty Sale", u8"空販売" },
	LocalizedText{ "Harvest", u8"収穫" },
	LocalizedText{ "Sold", u8"販売" },
	LocalizedText{ "Input Lock", u8"クリア後入力" },
	LocalizedText{ "Restart", u8"リスタート" },
	LocalizedText{ "Restart Farm", u8"畑を最初からやり直す" },
	LocalizedText{ "Farm History", u8"操作履歴" },
	LocalizedText{ "CG5 Demo", u8"CG5デモ" },
	LocalizedText{ "Console", u8"コンソール" },
	LocalizedText{ "Editor Settings", u8"エディター設定" },
	LocalizedText{ "Scene Visibility", u8"シーン表示" },
	LocalizedText{ "Fullscreen PostEffect", u8"フルスクリーンPostEffect" },
	LocalizedText{ "PostEffect Workspace###Fullscreen PostEffect", u8"PostEffectワークスペース###Fullscreen PostEffect" },
	LocalizedText{ "Pipeline Status", u8"パイプライン状態" },
	LocalizedText{ "Mode", u8"モード" },
	LocalizedText{ "Single", u8"単体" },
	LocalizedText{ "Chain", u8"チェーン" },
	LocalizedText{ "Active Effect", u8"適用中のEffect" },
	LocalizedText{ "Multiple Passes", u8"複数Pass" },
	LocalizedText{ "CG5 Quick Check", u8"CG5クイック確認" },
	LocalizedText{ "Scored Effects", u8"加点対象Effect" },
	LocalizedText{ "Presets disable Chain Mode for a stable comparison.", u8"比較を安定させるためPreset適用時はChain ModeをOFFにします。" },
	LocalizedText{ "Gaussian Filter (+5)", u8"Gaussian Filter (+5)" },
	LocalizedText{ "Gaussian Sigma", u8"Gaussian Sigma" },
	LocalizedText{ "Effect Mode", u8"Effectモード" },
	LocalizedText{ "PostEffect Chain Mode", u8"PostEffect Chain Mode" },
	LocalizedText{ "Fullscreen Effect", u8"単体Effect" },
	LocalizedText{ "Enabled Passes", u8"有効Pass数" },
	LocalizedText{ "Parameter Target", u8"パラメーター対象" },
	LocalizedText{ "Selected Effect Parameters", u8"選択Effectのパラメーター" },
	LocalizedText{ "This effect has no adjustable parameters.", u8"このEffectには調整項目がありません。" },
	LocalizedText{ "Kernel size is fixed by the selected effect.", u8"Kernelサイズは選択したEffectで固定されます。" },
	LocalizedText{ "No noise textures are loaded.", u8"Noise Textureが読み込まれていません。" },
	LocalizedText{ "Pipeline Details", u8"パイプライン詳細" },
	LocalizedText{ "Chain Mode", u8"Chain Mode" },
	LocalizedText{ "Reset All PostEffect Parameters", u8"PostEffectパラメーターをすべて初期化" },
	LocalizedText{ "Farm Map###FarmMap", u8"畑マップ###FarmMap" },
	LocalizedText{ "Farm Hierarchy###FarmHierarchy", u8"畑階層###FarmHierarchy" },
	LocalizedText{ "Game Viewport###GameViewport", u8"ゲームビュー###GameViewport" },
	LocalizedText{ "Farm Inspector###FarmInspector", u8"畑インスペクター###FarmInspector" },
	LocalizedText{ "Farm History###FarmHistory", u8"操作履歴###FarmHistory" },
	LocalizedText{ "CG5 Demo###CG5Demo", u8"CG5デモ###CG5Demo" },
	LocalizedText{ "Console###Console", u8"コンソール###Console" },
	LocalizedText{ "Farm Toolbar###FarmToolbar", u8"畑ツールバー###FarmToolbar" },
	LocalizedText{ "Editor Settings###EditorSettings", u8"エディター設定###EditorSettings" },
	LocalizedText{ "Scene Visibility###Visibility & Cull", u8"シーン表示###Visibility & Cull" },
	LocalizedText{ "Visible", u8"表示中" },
	LocalizedText{ "Debug visualizations are visible.", u8"デバッグ表示が有効です。" },
	LocalizedText{ "Debug visualizations are hidden.", u8"デバッグ表示は非表示です。" },
	LocalizedText{ "Quick Presets", u8"クイックプリセット" },
	LocalizedText{ "Show All###VisibilityShowAll", u8"すべて表示###VisibilityShowAll" },
	LocalizedText{ "Hide Debug###VisibilityHideDebug", u8"デバッグ非表示###VisibilityHideDebug" },
	LocalizedText{ "Farm Editing###VisibilityFarmEditing", u8"畑編集###VisibilityFarmEditing" },
	LocalizedText{ "Clean Capture###VisibilityCleanCapture", u8"撮影用###VisibilityCleanCapture" },
	LocalizedText{ "Reset###VisibilityReset", u8"初期状態に戻す###VisibilityReset" },
	LocalizedText{ "Show every Scene object and debug visualization.", u8"すべてのScene Objectとデバッグ表示を有効にします。" },
	LocalizedText{ "Keep Scene objects visible and hide only debug helpers.", u8"Scene Objectを維持し、デバッグ補助表示だけを隠します。" },
	LocalizedText{ "Show the Farm, Level objects, and effects without test objects.", u8"テスト用Objectを隠し、畑・Level Object・エフェクトを表示します。" },
	LocalizedText{ "Show only the Farm, HUD, and effect particles for recording.", u8"録画用に畑・HUD・エフェクトParticleだけを表示します。" },
	LocalizedText{ "Editing", u8"編集対象" },
	LocalizedText{ "Edit Focus", u8"編集対象" },
	LocalizedText{ "Scene Objects", u8"シーンオブジェクト" },
	LocalizedText{ "Sphere", u8"Sphere" },
	LocalizedText{ "Plane", u8"Plane" },
	LocalizedText{ "Sprite (2D)", u8"Sprite (2D)" },
	LocalizedText{ "Particles", u8"Particle" },
	LocalizedText{ "Animated Model", u8"Animation Model" },
	LocalizedText{ "Level Objects", u8"Level Object" },
	LocalizedText{ "Farm Visualization", u8"畑表示" },
	LocalizedText{ "Farm grid and tile selection stay visible.", u8"畑Gridと選択枠は常に表示されます。" },
	LocalizedText{ "Debug Gizmos", u8"デバッグGizmo" },
	LocalizedText{ "Skeleton Debug", u8"Skeleton Debug" },
	LocalizedText{ "Level Gizmos", u8"Level Gizmo" },
	LocalizedText{ "Collision Gizmos", u8"Collision Gizmo" },
	LocalizedText{ "Level object bounds, routes, cameras, lights, and trigger helpers.", u8"Level Objectの境界、経路、Camera、Light、Trigger補助表示です。" },
	LocalizedText{ "Runtime collider bounds. This includes the large cyan debug box.", u8"実行時Colliderの範囲です。大きな水色のDebug Boxも含みます。" },
	LocalizedText{ "Advanced Rendering", u8"詳細描画設定" },
	LocalizedText{ "Cull Mode", u8"Cull Mode" },
	LocalizedText{ "Editor Appearance", u8"エディター表示設定" },
	LocalizedText{ "UI Scale", u8"UI倍率" },
	LocalizedText{ "Theme", u8"テーマ" },
	LocalizedText{ "Reset Window Layout", u8"ウィンドウ配置を初期化" },
	LocalizedText{ "Saved to %s", u8"設定保存先: %s" },
	LocalizedText{ "New", u8"新規作成" },
	LocalizedText{ "Create an empty Farm document", u8"空の畑データを新規作成します" },
	LocalizedText{ "Saves...", u8"セーブ一覧..." },
	LocalizedText{ "View, search, load, or rename saved Farm documents", u8"保存済みの畑データを検索、読込、名前変更します" },
	LocalizedText{ "Save", u8"上書き保存" },
	LocalizedText{ "Ctrl+S: Save changes", u8"Ctrl+S: 変更を上書き保存" },
	LocalizedText{ "Farm document is already saved", u8"変更は保存済みです" },
	LocalizedText{ "Name and save this Farm document", u8"この畑データに名前を付けて保存します" },
	LocalizedText{ "Save As...", u8"名前を付けて保存..." },
	LocalizedText{ "Save a copy with a new name (Japanese is supported)", u8"新しい名前でコピーを保存します（日本語対応）" },
	LocalizedText{ "NEW", u8"新規" },
	LocalizedText{ "UNSAVED", u8"未保存" },
	LocalizedText{ "SAVED", u8"保存済み" },
	LocalizedText{ "ERROR", u8"エラー" },
	LocalizedText{ "Clear", u8"クリア" },
	LocalizedText{ "Info", u8"情報" },
	LocalizedText{ "Warning", u8"警告" },
	LocalizedText{ "Error", u8"エラー" },
	LocalizedText{ "Search logs...", u8"ログを検索..." },
	LocalizedText{ "Auto-scroll", u8"自動スクロール" },
	LocalizedText{ "Time", u8"時刻" },
	LocalizedText{ "Level", u8"種類" },
	LocalizedText{ "Message", u8"メッセージ" },
	LocalizedText{ "Selected log", u8"選択中のログ" },
	LocalizedText{ "No logs match the current filters.", u8"現在の条件に一致するログはありません。" },
	LocalizedText{ "Resume simulation", u8"シミュレーションを再開" },
	LocalizedText{ "Pause simulation", u8"シミュレーションを一時停止" },
	LocalizedText{ "Advance one simulation step", u8"シミュレーションを1ステップ進める" },
	LocalizedText{ "PLAYING", u8"実行中" },
	LocalizedText{ "PAUSED", u8"一時停止" },
	LocalizedText{ "Simulation Tick", u8"シミュレーションTick" },
	LocalizedText{ "Required Effect", u8"必須エフェクト" },
	LocalizedText{ "READY", u8"準備完了" },
	LocalizedText{ "NOT ACTIVE", u8"未適用" },
	LocalizedText{ "Compare the same Farm scene before and after Grayscale.", u8"同じFarm SceneでGrayscale適用前後を比較します。" },
	LocalizedText{ "Original Color", u8"元のカラー" },
	LocalizedText{ "Required Grayscale", u8"必須 Grayscale" },
	LocalizedText{ "Current Effect", u8"現在のEffect" },
	LocalizedText{ "Bonus Effect", u8"加点エフェクト" },
	LocalizedText{ "Highlight Farm depth boundaries for the scored bonus demo.", u8"畑の深度境界を強調し、加点対象のOutlineを確認します。" },
	LocalizedText{ "Depth-Based Outline", u8"Depth-Based Outline" },
	LocalizedText{ "Depth Threshold", u8"深度しきい値" },
	LocalizedText{ "Outline Intensity", u8"Outline強度" },
	LocalizedText{ "Outline Thickness", u8"Outline太さ" },
	LocalizedText{ "Linearize Depth", u8"Depthを線形化" },
	LocalizedText{ "Hoe", u8"耕す" },
	LocalizedText{ "Water", u8"水やり" },
	LocalizedText{ "Seed", u8"植える" },
	LocalizedText{ "Harvest", u8"収穫" },
	LocalizedText{ "Undo", u8"元に戻す" },
	LocalizedText{ "Redo", u8"やり直す" },
	LocalizedText{ "No Farm edit to undo", u8"元に戻せる畑操作はありません" },
	LocalizedText{ "No Farm edit to redo", u8"やり直せる畑操作はありません" },
	LocalizedText{ "No tile selected", u8"畑マスが選択されていません" },
	LocalizedText{ "Tile #%d", u8"畑マス #%d" },
	LocalizedText{ "Reset Layout", u8"レイアウト初期化" },
	LocalizedText{ "Discard unsaved Farm edits?###FarmDiscardChanges", u8"未保存の畑編集を破棄しますか？###FarmDiscardChanges" },
	LocalizedText{ "The current Farm has unsaved changes.", u8"現在の畑データには未保存の変更があります。" },
	LocalizedText{ "Continuing will discard those edits.", u8"続行すると変更内容は失われます。" },
	LocalizedText{ "Cancel", u8"キャンセル" },
	LocalizedText{ "Discard", u8"破棄して続行" },
	LocalizedText{ "Save Farm As###FarmSaveAs", u8"名前を付けて保存###FarmSaveAs" },
	LocalizedText{ "Farm name", u8"セーブ名" },
	LocalizedText{ "Japanese names are stored as UTF-8. The filename remains safe and internal.", u8"日本語名はUTF-8で保存され、内部ファイル名には使用されません。" },
	LocalizedText{ "Farm Saves###FarmSaves", u8"セーブデータ###FarmSaves" },
	LocalizedText{ "Saved Farms (%zu)", u8"セーブデータ (%zu件)" },
	LocalizedText{ "Select a save to load or rename it", u8"読込または名前変更するデータを選択してください" },
	LocalizedText{ "Search by name...", u8"名前で検索..." },
	LocalizedText{ "Name", u8"名前" },
	LocalizedText{ "Saved", u8"保存日時" },
	LocalizedText{ "[Open] ", u8"[使用中] " },
	LocalizedText{ "Selected: %s%s", u8"選択中: %s%s" },
	LocalizedText{ " (currently open)", u8"（現在使用中）" },
	LocalizedText{ "No Farm saves yet. Use Save As to create one.", u8"セーブデータがありません。「名前を付けて保存」で作成してください。" },
	LocalizedText{ "Close", u8"閉じる" },
	LocalizedText{ "Load Selected", u8"選択データを読み込む" },
	LocalizedText{ "Rename...", u8"名前変更..." },
	LocalizedText{ "Rename selected save", u8"選択したセーブの名前変更" },
	LocalizedText{ "The internal save ID and file path will not change.", u8"内部IDと保存ファイルの場所は変更されません。" },
	LocalizedText{ "Cancel Rename", u8"名前変更を中止" },
	LocalizedText{ "Apply Rename", u8"名前を変更" },
	LocalizedText{ "Delete...", u8"削除..." },
	LocalizedText{ "Delete selected save", u8"選択したセーブを削除" },
	LocalizedText{ "Delete Farm Save###FarmDeleteSave", u8"セーブデータを削除###FarmDeleteSave" },
	LocalizedText{ "Delete \"%s\"?", u8"「%s」を削除しますか？" },
	LocalizedText{ "This operation cannot be undone.", u8"この操作は元に戻せません。" },
	LocalizedText{ "The current Farm will remain open as an unsaved document.", u8"現在の畑は未保存データとして開いたまま残ります。" },
	LocalizedText{ "Delete Save", u8"セーブを削除" },
	LocalizedText{ "Farm data is unavailable.", u8"畑データを利用できません。" },
	LocalizedText{ "Farm Grid  %d x %d", u8"畑グリッド  %d x %d" },
	LocalizedText{ "Click a tile to select it", u8"畑マスをクリックして選択" },
	LocalizedText{ "Empty", u8"未耕作" },
	LocalizedText{ "Tilled", u8"耕し済み" },
	LocalizedText{ "Watered", u8"水やり済み" },
	LocalizedText{ "Planted", u8"植え付け済み" },
	LocalizedText{ "Growing", u8"成長中" },
	LocalizedText{ "Sprout", u8"芽生え" },
	LocalizedText{ "Almost Ready", u8"収穫間近" },
	LocalizedText{ "Ready", u8"収穫可能" },
	LocalizedText{ "TestCrop", u8"カブ" },
	LocalizedText{ "Carrot", u8"ニンジン" },
	LocalizedText{ "Tomato", u8"トマト" },
	LocalizedText{ "Pumpkin", u8"かぼちゃ" },
	LocalizedText{ "Legend", u8"凡例" },
	LocalizedText{ "Blue bar: moisture", u8"青いバー: 水分量" },
	LocalizedText{ "Green/gold bar: growth", u8"緑・金のバー: 成長度" },
	LocalizedText{ "Tile %d  (%d, %d)", u8"畑マス %d  (%d, %d)" },
	LocalizedText{ "State: %s", u8"状態: %s" },
	LocalizedText{ "Height: H%d", u8"高さ: H%d" },
	LocalizedText{ "Moisture: %.0f%%", u8"水分量: %.0f%%" },
	LocalizedText{ "Growth: %.0f%%", u8"成長度: %.0f%%" },
	LocalizedText{ "Selection", u8"選択中の畑マス" },
	LocalizedText{ "Coordinate (%d, %d)", u8"座標 (%d, %d)" },
	LocalizedText{ "Crop: %s", u8"作物: %s" },
	LocalizedText{ "Terrain", u8"地形" },
	LocalizedText{ "Height", u8"高さ" },
	LocalizedText{ "Feature: %s", u8"地形機能: %s" },
	LocalizedText{ "Canal", u8"用水路" },
	LocalizedText{ "Dry Canal", u8"未通水" },
	LocalizedText{ "Supplied", u8"通水中" },
	LocalizedText{ "Water Source", u8"水源" },
	LocalizedText{ "Irrigation Network", u8"灌漑ネットワーク" },
	LocalizedText{ "Farm placeholder meshes", u8"畑の仮モデルを表示" },
	LocalizedText{ "Farm mesh parts: %d", u8"畑の描画部品数: %d" },
	LocalizedText{ "Farm meshes unavailable or over limit; debug lines remain.", u8"モデル未読込または部品数上限。デバッグ線を表示します。" },
	LocalizedText{ "Crop view", u8"作物表示" },
	LocalizedText{ "Water view", u8"水分表示" },
	LocalizedText{ "Water map: soil moisture / reservoir stock (%)", u8"数値：畑は土壌水分、水路・水源は貯水率（%）" },
	LocalizedText{ "Cyan dot: soil received water in the last step (history while paused)", u8"水色の点：直前に受水した畑（停止中は履歴）" },
	LocalizedText{ "Soil: brown = low moisture, blue = high moisture; dash = no irrigation access", u8"畑の色：茶色は乾燥、青色は多水分。「-」は給水経路なし。" },
	LocalizedText{ "Last Irrigation Step", u8"直前の給水実績" },
	LocalizedText{ "No valid measurement; run the farm after editing.", u8"計測なし。編集後に畑の時間を進めてください。" },
	LocalizedText{ "Last fixed step, not a rate. 1 unit = one full reservoir. Pause keeps history.", u8"直前1ステップの実績（毎秒量ではありません）。1単位＝水路1マスの満水量。停止中は履歴を表示します。" },
	LocalizedText{ "Simulated time: %.4f s", u8"経過時間: %.4f 秒" },
	LocalizedText{ "Stock before: %.4f", u8"計測前の貯水: %.4f" },
	LocalizedText{ "Source refill: +%.4f", u8"水源の補給: +%.4f" },
	LocalizedText{ "Internal transfer: %.4f", u8"水路内の移送: %.4f" },
	LocalizedText{ "Delivered to soil: %.4f", u8"畑への給水: %.4f" },
	LocalizedText{ "Stock after: %.4f", u8"計測後の貯水: %.4f" },
	LocalizedText{ "Balance residual: %.7f", u8"水収支の誤差: %.7f" },
	LocalizedText{ "Selected Tile Delivery", u8"選択マスの給水実績" },
	LocalizedText{ "Canal in / out: %.4f / %.4f", u8"水路の流入 / 流出: %.4f / %.4f" },
	LocalizedText{ "Soil received: %.4f", u8"この畑の受水: %.4f" },
	LocalizedText{ "Sent to adjacent soil: %.4f", u8"隣の畑への給水: %.4f" },
	LocalizedText{ "Sources %d / Supplied canals %d / Irrigation range %d", u8"水源 %d / 接続用水路 %d / 接続範囲 %d" },
	LocalizedText{ "Irrigation range: %s", u8"水源への接続範囲: %s" },
	LocalizedText{ "Water available", u8"給水可能" },
	LocalizedText{ "Wet", u8"給水可" },
	LocalizedText{ "Stored", u8"残水" },
	LocalizedText{ "Waiting", u8"待機" },
	LocalizedText{ "Retained water", u8"残水あり" },
	LocalizedText{ "Automatic soil intake", u8"この畑の自動給水" },
	LocalizedText{ "Closed intake keeps soil moisture and canal water. Manual watering still works.", u8"切っても土の水分・水路の水は残ります。じょうろは使用できます。" },
	LocalizedText{ "Waiting for water", u8"補給待ち" },
	LocalizedText{ "Water depleted", u8"水切れ" },
	LocalizedText{ "No irrigation access", u8"給水経路なし" },
	LocalizedText{ "Availability is not measured delivery. Soil receives water only after cultivation.", u8"現在の給水条件です。実際の給水量ではありません。畑への給水は耕作後に始まります。" },
	LocalizedText{ "In range", u8"範囲内" },
	LocalizedText{ "Out of range", u8"範囲外" },
	LocalizedText{ "Supplied by canal #%d", u8"水源への接続経路: 用水路 #%d" },
	LocalizedText{ "Irrigation active", u8"灌漑中" },
	LocalizedText{ "Supply strength: %.0f%%", u8"接続上の供給強度: %.0f%%" },
	LocalizedText{ "Stored water: %.0f%%", u8"貯水量: %.0f%%" },
	LocalizedText{ "Stored water remains after disconnection; removal discards it.", u8"切断後も残水は使用できます。撤去すると水も失われます。" },
	LocalizedText{ "Recovery forecast is an upper bound while water remains; sharing reduces it.", u8"給水予測は残水がある間の上限です。複数マスへの配分で低下します。" },
	LocalizedText{ "Blue bar: soil moisture / stored canal water", u8"青いバー: 畑の水分 / 用水路の貯水量" },
	LocalizedText{ "Irrigation strength: %.0f%%", u8"経路上の灌漑強度: %.0f%%" },
	LocalizedText{ "Downstream canals: %d", u8"下流の用水路: %d" },
	LocalizedText{ "Irrigation recovery: %.1f%% / sec", u8"灌漑回復: %.1f%% / 秒" },
	LocalizedText{ "Net moisture: %+.1f%% / sec", u8"水分収支: %+.1f%% / 秒" },
	LocalizedText{ "Full moisture ETA: %.1f sec", u8"満水まで: %.1f秒" },
	LocalizedText{ "Cyan line: irrigation range", u8"水色線: 灌漑範囲" },
	LocalizedText{ "Cyan line: supply strength", u8"水色線: 供給強度" },
	LocalizedText{ "Irrigation Preview", u8"灌漑プレビュー" },
	LocalizedText{ "Canal Brush", u8"用水路ブラシ" },
	LocalizedText{ "Move along one row or column; turn at a tile", u8"同じ行・列へ移動してください。曲がり角で一度止めます" },
	LocalizedText{ "Canal path blocked at tile #%d", u8"マス #%d を通れないため、区間を追加していません" },
	LocalizedText{ "Straight drags fill skipped tiles", u8"直線ドラッグは途中のマスも自動で接続" },
	LocalizedText{ "Place canals", u8"設置" },
	LocalizedText{ "Erase canals", u8"撤去" },
	LocalizedText{ "Canal removal: %d tiles", u8"撤去候補: %dマス" },
	LocalizedText{ "Farm time paused during preview", u8"プレビュー中は農地の時間を停止" },
	LocalizedText{ "Drag over canals; return along the path to shorten it", u8"用水路をドラッグ。経路を引き返すと候補を短縮" },
	LocalizedText{ "Drag over empty tiles; return along the path to shorten it", u8"空きマスをドラッグ。経路を引き返すと候補を短縮" },
	LocalizedText{ "Drag across adjacent empty tiles to preview a canal path", u8"隣接する空きマスをドラッグして用水路を仮配置" },
	LocalizedText{ "Drag across adjacent empty tiles", u8"隣接する空きマスをドラッグ" },
	LocalizedText{ "Canal path: %d tiles", u8"用水路候補: %dマス" },
	LocalizedText{ "Release the mouse, inspect the result, then confirm", u8"マウスを離して結果を確認し、変更を確定してください" },
	LocalizedText{ "Tile #%d: %s -> %s", u8"畑マス #%d: %s -> %s" },
	LocalizedText{ "Tile #%d: H%d -> H%d", u8"畑マス #%d: H%d -> H%d" },
	LocalizedText{ "Preview: Sources %d / Canals %d / Range %d", u8"予測: 水源 %d / 通水用水路 %d / 灌漑範囲 %d" },
	LocalizedText{ "Farm changed. Cancel and preview again.", u8"農地が変更されました。取り消して再度プレビューしてください。" },
	LocalizedText{ "Confirm Preview", u8"この変更を確定" },
	LocalizedText{ "Harvest size: %.2fx baseline", u8"収穫サイズ: 基準の %.2f 倍" },
	LocalizedText{ "Harvest size forecast: %.2fx baseline", u8"収穫サイズ予測: 基準の %.2f 倍" },
	LocalizedText{ "Size unknown: no recorded care/size data.", u8"サイズ不明: 育成履歴またはサイズ記録がありません" },
	LocalizedText{ "Size uses recorded water and nutrient care. Baseline 1x; forecast may change. Not current model scale.", u8"水分・養分の育成履歴から算出。基準1倍。予測は変動します。現在のモデルの大きさではありません。" },
	LocalizedText{ "Height candidates: %d tiles", u8"高さ変更の候補: %d マス" },
	LocalizedText{ "Drag to add height candidates; each tile changes once before confirmation.", u8"左ドラッグでマスを追加。確定までは各マス1段だけ変更します。" },
	LocalizedText{ "Only the displayed candidates will be confirmed; the rejected segment is excluded.", u8"確定するのは表示中の候補だけです。追加できなかった区間は含みません。" },
	LocalizedText{ "Cancel Preview", u8"プレビューを取消" },
	LocalizedText{ "Preview Canal Removal", u8"用水路の撤去をプレビュー" },
	LocalizedText{ "Preview Canal Placement", u8"用水路の設置をプレビュー" },
	LocalizedText{ "Preview Water Source Removal", u8"水源の撤去をプレビュー" },
	LocalizedText{ "Preview Water Source Placement", u8"水源の設置をプレビュー" },
	LocalizedText{ "Preview changed tile", u8"プレビュー変更対象" },
	LocalizedText{ "Preview canal change on selected tile", u8"選択マスの用水路変更を仮計算" },
	LocalizedText{ "Preview water source change on selected tile", u8"選択マスの水源変更を仮計算" },
	LocalizedText{ "Preview lowering selected tile", u8"選択マスを下げた結果を仮計算" },
	LocalizedText{ "Preview raising selected tile", u8"選択マスを上げた結果を仮計算" },
	LocalizedText{ "Place Canal", u8"用水路を作る" },
	LocalizedText{ "Remove Canal", u8"通常地面に戻す" },
	LocalizedText{ "Toggle canal on selected tile (N)", u8"選択マスの用水路を切り替え (N)" },
	LocalizedText{ "Next: press N to restore normal ground.", u8"次: Nで通常地面に戻す。" },
	LocalizedText{ "Place Water Source", u8"水源を作る" },
	LocalizedText{ "Remove Water Source", u8"水源を撤去する" },
	LocalizedText{ "Toggle water source on selected tile (M)", u8"選択マスの水源を切り替え (M)" },
	LocalizedText{ "Supplied from a water source. N removes this canal.", u8"水源から通水中。Nで用水路を撤去。" },
	LocalizedText{ "Dry canal: connect it to an equal or higher water source.", u8"未通水: 同じ高さか高い水源へ接続してください。" },
	LocalizedText{ "Next: connect a canal or press M to remove the source.", u8"次: 用水路を接続、またはMで水源を撤去。" },
	LocalizedText{ "Lower selected tile (Page Down)", u8"選択中の畑マスを下げます（Page Down）" },
	LocalizedText{ "Raise selected tile (Page Up)", u8"選択中の畑マスを上げます（Page Up）" },
	LocalizedText{ "Crop Status", u8"作物の状態" },
	LocalizedText{ "Stage: %s", u8"成長段階: %s" },
	LocalizedText{ "Moisture: %s", u8"水分状態: %s" },
	LocalizedText{ "Excess water", u8"水過多" },
	LocalizedText{ "Excess water: reduce irrigation and wait.", u8"水過多です。給水を減らして水分が下がるのを待ちます。" },
	LocalizedText{ "Optimal moisture: %.0f%% - %.0f%%", u8"適量の範囲: %.0f%% ～ %.0f%%" },
	LocalizedText{ "Watering: %.0f%% -> %.0f%%", u8"水やり: %.0f%% → %.0f%%" },
	LocalizedText{ "Added moisture: %.0f percentage points", u8"今回の追加水分: %.0fポイント" },
	LocalizedText{ "One dose per press. Irrigation and drying are separate.", u8"1回押すごとに給水。用水路の給水・乾燥は別に進みます。" },
	LocalizedText{ "Growth efficiency: %.0f%% (optimal = 100%%)", u8"成長効率: %.0f%%（適量時を100%%）" },
	LocalizedText{ "Below range: too dry. Above range: excess water slows growth.", u8"範囲未満は水不足、範囲超過は水過多で成長が遅くなります。" },
	LocalizedText{ "Dry", u8"乾燥" },
	LocalizedText{ "Low", u8"水不足" },
	LocalizedText{ "Good", u8"適湿" },
	LocalizedText{ "Unavailable", u8"対象外" },
	LocalizedText{ "Growth profile: %s", u8"成長特性: %s" },
	LocalizedText{ "Good moisture: %.0f%% or more", u8"適湿条件: %.0f%%以上" },
	LocalizedText{ "Growth rate: %.1f%% / sec", u8"成長速度: %.1f%% / 秒" },
	LocalizedText{ "Ready ETA: %.1f sec (current rate)", u8"収穫まで: 約%.1f秒（現在速度）" },
	LocalizedText{ "Dry ETA: %.1f sec", u8"乾燥まで: 約%.1f秒" },
	LocalizedText{ "No active growth forecast", u8"成長予測の対象外です" },
	LocalizedText{ "Crop Care History", u8"育成中の水分履歴" },
	LocalizedText{ "Soil Care", u8"土づくり" },
	LocalizedText{ "Soil Nutrients", u8"土の養分" },
	LocalizedText{ "Nutrient Balance", u8"養分充足度" },
	LocalizedText{ "Nutrients: %.0f / 100 (crop target %.0f)", u8"養分: %.0f / 100（作物の目安 %.0f）" },
	LocalizedText{ "Compost before planting. Nutrients are consumed as crops grow; shortage lowers quality.", u8"植える前に堆肥を混ぜます。成長に伴い養分を消費し、不足すると品質点が下がります。" },
	LocalizedText{ "Add Compost (Free)", u8"堆肥を混ぜる（無料）" },
	LocalizedText{ "Observed growing time: %.1f sec", u8"記録した生育時間: %.1f秒" },
	LocalizedText{ "Dry %.0f%% / Low %.0f%%", u8"乾燥 %.0f%% / 不足 %.0f%%" },
	LocalizedText{ "Good %.0f%% / Excess %.0f%%", u8"適量 %.0f%% / 過多 %.0f%%" },
	LocalizedText{ "Average growth efficiency: %.0f%%", u8"期間平均の成長効率: %.0f%%" },
	LocalizedText{ "Water Balance uses this full-period average, not only the current moisture.", u8"水分バランス点は現在値だけでなく、育成期間全体の平均から計算します。" },
	LocalizedText{ "Care history starts when growth time advances.", u8"時間を進めると育成履歴の記録を開始します。" },
	LocalizedText{ "Crop Quality", u8"作物品質" },
	LocalizedText{ "Selected Tile Preview", u8"選択マスの収穫予測" },
	LocalizedText{ "Last Harvest Result", u8"直近の収穫結果" },
	LocalizedText{ "No quality data", u8"品質データなし" },
	LocalizedText{ "Next crop: wait for full maturity before harvesting.", u8"次回：成長１００％まで育てて収穫" },
	LocalizedText{ "Maturity: wait for 100% growth before harvesting.", u8"成熟度：成長１００％まで待って収穫" },
	LocalizedText{ "Water: avoid both shortage and excess while growing.", u8"水分：育成中の水不足と水過多を避ける" },
	LocalizedText{ "Next crop: prepare a suitable height before planting.", u8"地形：次回は植付け前に作物向けの高さへ" },
	LocalizedText{ "Next crop: mix compost before planting.", u8"養分：次回は植付け前に堆肥を混ぜる" },
	LocalizedText{ "All recorded axes are in good condition.", u8"記録された各項目は良好です" },
	LocalizedText{ "Some axes are unknown; treat this evaluation as partial.", u8"不明な項目あり。評価は参考値です" },
	LocalizedText{ "Lowest known axis: %d / 100", u8"見直す項目（既知の最低値）：%d / 100" },
	LocalizedText{ "Unknown axes are excluded from the hint.", u8"不明な項目はヒントの選定から除外しています" },
	LocalizedText{ "Maturity", u8"成熟度" },
	LocalizedText{ "Water Balance", u8"水分バランス" },
	LocalizedText{ "Terrain Fit", u8"地形適性" },
	LocalizedText{ "Score: %d / 100  Grade %s", u8"総合: %d / 100  ランク %s" },
	LocalizedText{ "Estimated Value: %dG (Base %dG)", u8"予想売価: %dG (基本 %dG)" },
	LocalizedText{ "Growth", u8"成長度" },
	LocalizedText{ "Next: select Harvest and apply.", u8"次の操作: 「収穫」を選んで適用" },
	LocalizedText{ "Next: select Hoe to prepare this tile.", u8"次の操作: 「耕す」を選んで土を準備" },
	LocalizedText{ "Next: select Seed to plant.", u8"次の操作: 「植える」を選んで作物を植える" },
	LocalizedText{ "Next: Water this tile or plant a Seed.", u8"次の操作: 水やり、または作物を植える" },
	LocalizedText{ "Growing slowly: add Water.", u8"水分不足で成長が遅れています。水やりしてください。" },
	LocalizedText{ "Growing: wait until the crop is ready.", u8"成長中です。収穫可能になるまで待ってください。" },
	LocalizedText{ "Farm Tool", u8"農具" },
	LocalizedText{ "1  Hoe", u8"1  耕す" },
	LocalizedText{ "2  Water", u8"2  水やり" },
	LocalizedText{ "3  Seed", u8"3  植える" },
	LocalizedText{ "4  Harvest", u8"4  収穫" },
	LocalizedText{ "Action available", u8"この操作を実行できます" },
	LocalizedText{ "Already fully watered", u8"水分量はすでに最大です" },
	LocalizedText{ "Crop is not ready", u8"作物はまだ収穫できません" },
	LocalizedText{ "No valid tile", u8"有効な畑マスがありません" },
	LocalizedText{ "Tool is unavailable", u8"この農具は使用できません" },
	LocalizedText{ "Tool does not match tile state", u8"現在の畑状態ではこの農具を使えません" },
	LocalizedText{ "Apply Selected Tool", u8"選択中の農具を適用" },
	LocalizedText{ "Viewport Shortcuts", u8"ゲームビュー操作" },
	LocalizedText{ "Click: select   Shift+Click: select and apply", u8"クリック: 選択   Shift+クリック: 選択して適用" },
	LocalizedText{ "Arrows: move   Q/E: tool   Enter: apply", u8"矢印キー: 選択移動   Q/E: 農具切替   Enter: 適用" },
	LocalizedText{ "None", u8"なし" },
	LocalizedText{ "Undo %zu   Redo %zu   |   Ctrl+Z / Ctrl+Y", u8"元に戻す %zu   やり直す %zu   |   Ctrl+Z / Ctrl+Y" },
	LocalizedText{ "Next Undo: %s    |    Next Redo: %s", u8"次に戻す操作: %s    |    次にやり直す操作: %s" },
	LocalizedText{ "Hoe Tile", u8"畑を耕す" },
	LocalizedText{ "Water Tile", u8"水やり" },
	LocalizedText{ "Plant Seed", u8"作物を植える" },
	LocalizedText{ "Harvest Crop", u8"作物を収穫" },
	LocalizedText{ "Raise Tile", u8"畑マスを上げる" },
	LocalizedText{ "Lower Tile", u8"畑マスを下げる" },
	LocalizedText{ "Farm Tile Edit", u8"畑マスを編集" },
	LocalizedText{ "Scene / Farm", u8"シーン / 畑" },
	LocalizedText{ "Farm Grid", u8"畑グリッド" },
	LocalizedText{ "Farm Grid  (%d x %d)", u8"畑グリッド  (%d x %d)" },
	LocalizedText{ "Row %d", u8"行 %d" },
	LocalizedText{ "Tile %02d  [%s]", u8"畑マス %02d  [%s]" },
	LocalizedText{ "Coordinate (%d, %d)\nMoisture %.0f%%\nGrowth %.0f%%", u8"座標 (%d, %d)\n水分量 %.0f%%\n成長度 %.0f%%" },
	LocalizedText{ "Untitled Farm", u8"名称未設定の畑" },
	LocalizedText{ "New Farm document", u8"新しい畑データ" },
	LocalizedText{ "Use Save As to name this Farm document first.", u8"先に名前を付けて畑データを保存してください。" },
	LocalizedText{ "A Farm document with this name already exists.", u8"同じ名前の畑データがすでに存在します。" },
	LocalizedText{ "The selected Farm document no longer exists.", u8"選択した畑データは存在しません。" },
	LocalizedText{ "Could not read the selected Farm document.", u8"選択した畑データを読み込めませんでした。" },
	LocalizedText{ "Loaded the Farm, but could not remember it for the next launch.", u8"畑データは読み込みましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Loaded", u8"読み込みました" },
	LocalizedText{ "Farm name is unchanged", u8"畑の名前は変更されていません" },
	LocalizedText{ "Renamed", u8"名前を変更しました" },
	LocalizedText{ "Deleted", u8"削除しました" },
	LocalizedText{ "Deleted; current Farm is now unsaved", u8"削除しました。現在の畑は未保存状態です" },
	LocalizedText{ "New unsaved Farm", u8"未保存の新しい畑" },
	LocalizedText{ "Unsaved changes", u8"未保存の変更があります" },
	LocalizedText{ "Could not create or access the Farm save directory.", u8"畑の保存フォルダーを作成または参照できませんでした。" },
	LocalizedText{ "Saved the Farm, but could not remember it for the next launch.", u8"畑データは保存しましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Saved", u8"保存しました" },
	LocalizedText{ "Farm name cannot be empty.", u8"畑の名前を入力してください。" },
	LocalizedText{ "Farm name is too long.", u8"畑の名前が長すぎます。" },
	LocalizedText{ "Farm name is not valid UTF-8.", u8"畑の名前が正しいUTF-8文字列ではありません。" },
	LocalizedText{ "Farm name contains a control character.", u8"畑の名前に使用できない制御文字が含まれています。" },
	LocalizedText{ "The selected Farm document ID is invalid.", u8"選択した畑データのIDが不正です。" },
	LocalizedText{ "Could not prepare the Farm document for deletion.", u8"畑データを削除する準備ができませんでした。" },
	LocalizedText{ "Could not delete the selected Farm document.", u8"選択した畑データを削除できませんでした。" },
	LocalizedText{ "Could not refresh the Farm save list after deletion.", u8"削除後にセーブ一覧を更新できませんでした。" },
	LocalizedText{ "Could not update the Farm document catalog after deletion.", u8"削除後に畑データの管理情報を更新できませんでした。" },
};
} // namespace

const char* editor::Localize(EditorLanguage language, std::string_view englishText) noexcept {
	if (language == EditorLanguage::English) {
		return englishText.data();
	}
	for (const LocalizedText& text : kJapaneseText) {
		if (text.english == englishText) {
			return reinterpret_cast<const char*>(text.japanese.data());
		}
	}
	return englishText.data();
}

const char* editor::GetEditorLanguageStorageName(EditorLanguage language) noexcept {
	return language == EditorLanguage::English ? "English" : "Japanese";
}

EditorLanguage editor::ParseEditorLanguage(std::string_view value) noexcept {
	return value == "English" ? EditorLanguage::English : EditorLanguage::Japanese;
}
