#include "editor/EditorLocalization.h"

#include <array>

namespace {
struct LocalizedText {
	std::string_view english;
	std::u8string_view japanese;
};

constexpr std::array kJapaneseText = {
	LocalizedText{ "Farm Editor", u8"畑エディター" },
	LocalizedText{ "Display", u8"表示" },
	LocalizedText{ "Window", u8"ウィンドウ" },
	LocalizedText{ "Font", u8"フォント" },
	LocalizedText{ "Language", u8"表示言語" },
	LocalizedText{ "Japanese", u8"日本語" },
	LocalizedText{ "English", u8"English" },
	LocalizedText{ "Farm Map", u8"畑マップ" },
	LocalizedText{ "Farm Hierarchy", u8"畑階層" },
	LocalizedText{ "Farm Inspector", u8"畑インスペクター" },
	LocalizedText{ "Farm History", u8"操作履歴" },
	LocalizedText{ "Editor Settings", u8"エディター設定" },
	LocalizedText{ "Farm Map###FarmMap", u8"畑マップ###FarmMap" },
	LocalizedText{ "Farm Hierarchy###FarmHierarchy", u8"畑階層###FarmHierarchy" },
	LocalizedText{ "Game Viewport###GameViewport", u8"ゲームビュー###GameViewport" },
	LocalizedText{ "Farm Inspector###FarmInspector", u8"畑インスペクター###FarmInspector" },
	LocalizedText{ "Farm History###FarmHistory", u8"操作履歴###FarmHistory" },
	LocalizedText{ "Farm Toolbar###FarmToolbar", u8"畑ツールバー###FarmToolbar" },
	LocalizedText{ "Editor Settings###EditorSettings", u8"エディター設定###EditorSettings" },
	LocalizedText{ "Editor Appearance", u8"エディター表示設定" },
	LocalizedText{ "UI Scale", u8"UI倍率" },
	LocalizedText{ "Theme", u8"テーマ" },
	LocalizedText{ "Reset Window Layout", u8"ウィンドウ配置を初期化" },
	LocalizedText{ "Saved to %s", u8"設定保存先: %s" },
	LocalizedText{ "New", u8"新規作成" },
	LocalizedText{ "Create an empty Farm document", u8"空の畑データを新規作成します" },
	LocalizedText{ "Saves...", u8"セーブ一覧..." },
	LocalizedText{ "View, search, load, or rename saved Farm documents", u8"保存済みの畑データを検索、読込、名前変更します" },
	LocalizedText{ "Save", u8"上書き保存" },
	LocalizedText{ "Ctrl+S: Save changes", u8"Ctrl+S: 変更を上書き保存" },
	LocalizedText{ "Farm document is already saved", u8"変更は保存済みです" },
	LocalizedText{ "Name and save this Farm document", u8"この畑データに名前を付けて保存します" },
	LocalizedText{ "Save As...", u8"名前を付けて保存..." },
	LocalizedText{ "Save a copy with a new name (Japanese is supported)", u8"新しい名前でコピーを保存します（日本語対応）" },
	LocalizedText{ "NEW", u8"新規" },
	LocalizedText{ "UNSAVED", u8"未保存" },
	LocalizedText{ "SAVED", u8"保存済み" },
	LocalizedText{ "ERROR", u8"エラー" },
	LocalizedText{ "Hoe", u8"耕す" },
	LocalizedText{ "Water", u8"水やり" },
	LocalizedText{ "Seed", u8"植える" },
	LocalizedText{ "Harvest", u8"収穫" },
	LocalizedText{ "Undo", u8"元に戻す" },
	LocalizedText{ "Redo", u8"やり直す" },
	LocalizedText{ "No Farm edit to undo", u8"元に戻せる畑操作はありません" },
	LocalizedText{ "No Farm edit to redo", u8"やり直せる畑操作はありません" },
	LocalizedText{ "No tile selected", u8"畑マスが選択されていません" },
	LocalizedText{ "Tile #%d", u8"畑マス #%d" },
	LocalizedText{ "Reset Layout", u8"レイアウト初期化" },
	LocalizedText{ "Discard unsaved Farm edits?###FarmDiscardChanges", u8"未保存の畑編集を破棄しますか？###FarmDiscardChanges" },
	LocalizedText{ "The current Farm has unsaved changes.", u8"現在の畑データには未保存の変更があります。" },
	LocalizedText{ "Continuing will discard those edits.", u8"続行すると変更内容は失われます。" },
	LocalizedText{ "Cancel", u8"キャンセル" },
	LocalizedText{ "Discard", u8"破棄して続行" },
	LocalizedText{ "Save Farm As###FarmSaveAs", u8"名前を付けて保存###FarmSaveAs" },
	LocalizedText{ "Farm name", u8"セーブ名" },
	LocalizedText{ "Japanese names are stored as UTF-8. The filename remains safe and internal.", u8"日本語名はUTF-8で保存され、内部ファイル名には使用されません。" },
	LocalizedText{ "Farm Saves###FarmSaves", u8"セーブデータ###FarmSaves" },
	LocalizedText{ "Saved Farms (%zu)", u8"セーブデータ (%zu件)" },
	LocalizedText{ "Select a save to load or rename it", u8"読込または名前変更するデータを選択してください" },
	LocalizedText{ "Search by name...", u8"名前で検索..." },
	LocalizedText{ "Name", u8"名前" },
	LocalizedText{ "Saved", u8"保存日時" },
	LocalizedText{ "[Open] ", u8"[使用中] " },
	LocalizedText{ "Selected: %s%s", u8"選択中: %s%s" },
	LocalizedText{ " (currently open)", u8"（現在使用中）" },
	LocalizedText{ "No Farm saves yet. Use Save As to create one.", u8"セーブデータがありません。「名前を付けて保存」で作成してください。" },
	LocalizedText{ "Close", u8"閉じる" },
	LocalizedText{ "Load Selected", u8"選択データを読み込む" },
	LocalizedText{ "Rename...", u8"名前変更..." },
	LocalizedText{ "Rename selected save", u8"選択したセーブの名前変更" },
	LocalizedText{ "The internal save ID and file path will not change.", u8"内部IDと保存ファイルの場所は変更されません。" },
	LocalizedText{ "Cancel Rename", u8"名前変更を中止" },
	LocalizedText{ "Apply Rename", u8"名前を変更" },
	LocalizedText{ "Delete...", u8"削除..." },
	LocalizedText{ "Delete selected save", u8"選択したセーブを削除" },
	LocalizedText{ "Delete Farm Save###FarmDeleteSave", u8"セーブデータを削除###FarmDeleteSave" },
	LocalizedText{ "Delete \"%s\"?", u8"「%s」を削除しますか？" },
	LocalizedText{ "This operation cannot be undone.", u8"この操作は元に戻せません。" },
	LocalizedText{ "The current Farm will remain open as an unsaved document.", u8"現在の畑は未保存データとして開いたまま残ります。" },
	LocalizedText{ "Delete Save", u8"セーブを削除" },
	LocalizedText{ "Farm data is unavailable.", u8"畑データを利用できません。" },
	LocalizedText{ "Farm Grid  %d x %d", u8"畑グリッド  %d x %d" },
	LocalizedText{ "Click a tile to select it", u8"畑マスをクリックして選択" },
	LocalizedText{ "Empty", u8"未耕作" },
	LocalizedText{ "Tilled", u8"耕し済み" },
	LocalizedText{ "Watered", u8"水やり済み" },
	LocalizedText{ "Planted", u8"植え付け済み" },
	LocalizedText{ "Growing", u8"成長中" },
	LocalizedText{ "Ready", u8"収穫可能" },
	LocalizedText{ "TestCrop", u8"テスト作物" },
	LocalizedText{ "Legend", u8"凡例" },
	LocalizedText{ "Blue bar: moisture", u8"青いバー: 水分量" },
	LocalizedText{ "Green/gold bar: growth", u8"緑・金のバー: 成長度" },
	LocalizedText{ "Tile %d  (%d, %d)", u8"畑マス %d  (%d, %d)" },
	LocalizedText{ "State: %s", u8"状態: %s" },
	LocalizedText{ "Height: H%d", u8"高さ: H%d" },
	LocalizedText{ "Moisture: %.0f%%", u8"水分量: %.0f%%" },
	LocalizedText{ "Growth: %.0f%%", u8"成長度: %.0f%%" },
	LocalizedText{ "Selection", u8"選択中の畑マス" },
	LocalizedText{ "Coordinate (%d, %d)", u8"座標 (%d, %d)" },
	LocalizedText{ "Crop: %s", u8"作物: %s" },
	LocalizedText{ "Terrain", u8"地形" },
	LocalizedText{ "Height", u8"高さ" },
	LocalizedText{ "Lower selected tile (Page Down)", u8"選択中の畑マスを下げます（Page Down）" },
	LocalizedText{ "Raise selected tile (Page Up)", u8"選択中の畑マスを上げます（Page Up）" },
	LocalizedText{ "Crop Status", u8"作物の状態" },
	LocalizedText{ "Growth", u8"成長度" },
	LocalizedText{ "Next: select Harvest and apply.", u8"次の操作: 「収穫」を選んで適用" },
	LocalizedText{ "Next: select Hoe to prepare this tile.", u8"次の操作: 「耕す」を選んで土を準備" },
	LocalizedText{ "Next: select Seed to plant.", u8"次の操作: 「植える」を選んで作物を植える" },
	LocalizedText{ "Next: Water this tile or plant a Seed.", u8"次の操作: 水やり、または作物を植える" },
	LocalizedText{ "Growing slowly: add Water.", u8"水分不足で成長が遅れています。水やりしてください。" },
	LocalizedText{ "Growing: wait until the crop is ready.", u8"成長中です。収穫可能になるまで待ってください。" },
	LocalizedText{ "Farm Tool", u8"農具" },
	LocalizedText{ "1  Hoe", u8"1  耕す" },
	LocalizedText{ "2  Water", u8"2  水やり" },
	LocalizedText{ "3  Seed", u8"3  植える" },
	LocalizedText{ "4  Harvest", u8"4  収穫" },
	LocalizedText{ "Action available", u8"この操作を実行できます" },
	LocalizedText{ "Already fully watered", u8"水分量はすでに最大です" },
	LocalizedText{ "Crop is not ready", u8"作物はまだ収穫できません" },
	LocalizedText{ "No valid tile", u8"有効な畑マスがありません" },
	LocalizedText{ "Tool is unavailable", u8"この農具は使用できません" },
	LocalizedText{ "Tool does not match tile state", u8"現在の畑状態ではこの農具を使えません" },
	LocalizedText{ "Apply Selected Tool", u8"選択中の農具を適用" },
	LocalizedText{ "Viewport Shortcuts", u8"ゲームビュー操作" },
	LocalizedText{ "Click: select   Shift+Click: select and apply", u8"クリック: 選択   Shift+クリック: 選択して適用" },
	LocalizedText{ "Arrows: move   Q/E: tool   Enter: apply", u8"矢印キー: 選択移動   Q/E: 農具切替   Enter: 適用" },
	LocalizedText{ "None", u8"なし" },
	LocalizedText{ "Undo %zu   Redo %zu   |   Ctrl+Z / Ctrl+Y", u8"元に戻す %zu   やり直す %zu   |   Ctrl+Z / Ctrl+Y" },
	LocalizedText{ "Next Undo: %s    |    Next Redo: %s", u8"次に戻す操作: %s    |    次にやり直す操作: %s" },
	LocalizedText{ "Hoe Tile", u8"畑を耕す" },
	LocalizedText{ "Water Tile", u8"水やり" },
	LocalizedText{ "Plant Seed", u8"作物を植える" },
	LocalizedText{ "Harvest Crop", u8"作物を収穫" },
	LocalizedText{ "Raise Tile", u8"畑マスを上げる" },
	LocalizedText{ "Lower Tile", u8"畑マスを下げる" },
	LocalizedText{ "Farm Tile Edit", u8"畑マスを編集" },
	LocalizedText{ "Scene / Farm", u8"シーン / 畑" },
	LocalizedText{ "Farm Grid", u8"畑グリッド" },
	LocalizedText{ "Farm Grid  (%d x %d)", u8"畑グリッド  (%d x %d)" },
	LocalizedText{ "Row %d", u8"行 %d" },
	LocalizedText{ "Tile %02d  [%s]", u8"畑マス %02d  [%s]" },
	LocalizedText{ "Coordinate (%d, %d)\nMoisture %.0f%%\nGrowth %.0f%%", u8"座標 (%d, %d)\n水分量 %.0f%%\n成長度 %.0f%%" },
	LocalizedText{ "Untitled Farm", u8"名称未設定の畑" },
	LocalizedText{ "New Farm document", u8"新しい畑データ" },
	LocalizedText{ "Use Save As to name this Farm document first.", u8"先に名前を付けて畑データを保存してください。" },
	LocalizedText{ "A Farm document with this name already exists.", u8"同じ名前の畑データがすでに存在します。" },
	LocalizedText{ "The selected Farm document no longer exists.", u8"選択した畑データは存在しません。" },
	LocalizedText{ "Could not read the selected Farm document.", u8"選択した畑データを読み込めませんでした。" },
	LocalizedText{ "Loaded the Farm, but could not remember it for the next launch.", u8"畑データは読み込みましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Loaded", u8"読み込みました" },
	LocalizedText{ "Farm name is unchanged", u8"畑の名前は変更されていません" },
	LocalizedText{ "Renamed", u8"名前を変更しました" },
	LocalizedText{ "Deleted", u8"削除しました" },
	LocalizedText{ "Deleted; current Farm is now unsaved", u8"削除しました。現在の畑は未保存状態です" },
	LocalizedText{ "New unsaved Farm", u8"未保存の新しい畑" },
	LocalizedText{ "Unsaved changes", u8"未保存の変更があります" },
	LocalizedText{ "Could not create or access the Farm save directory.", u8"畑の保存フォルダーを作成または参照できませんでした。" },
	LocalizedText{ "Saved the Farm, but could not remember it for the next launch.", u8"畑データは保存しましたが、次回起動用の情報を保存できませんでした。" },
	LocalizedText{ "Saved", u8"保存しました" },
	LocalizedText{ "Farm name cannot be empty.", u8"畑の名前を入力してください。" },
	LocalizedText{ "Farm name is too long.", u8"畑の名前が長すぎます。" },
	LocalizedText{ "Farm name is not valid UTF-8.", u8"畑の名前が正しいUTF-8文字列ではありません。" },
	LocalizedText{ "Farm name contains a control character.", u8"畑の名前に使用できない制御文字が含まれています。" },
	LocalizedText{ "The selected Farm document ID is invalid.", u8"選択した畑データのIDが不正です。" },
	LocalizedText{ "Could not prepare the Farm document for deletion.", u8"畑データを削除する準備ができませんでした。" },
	LocalizedText{ "Could not delete the selected Farm document.", u8"選択した畑データを削除できませんでした。" },
	LocalizedText{ "Could not refresh the Farm save list after deletion.", u8"削除後にセーブ一覧を更新できませんでした。" },
	LocalizedText{ "Could not update the Farm document catalog after deletion.", u8"削除後に畑データの管理情報を更新できませんでした。" },
};
} // namespace

const char* editor::Localize(EditorLanguage language, std::string_view englishText) noexcept {
	if (language == EditorLanguage::English) {
		return englishText.data();
	}
	for (const LocalizedText& text : kJapaneseText) {
		if (text.english == englishText) {
			return reinterpret_cast<const char*>(text.japanese.data());
		}
	}
	return englishText.data();
}

const char* editor::GetEditorLanguageStorageName(EditorLanguage language) noexcept {
	return language == EditorLanguage::English ? "English" : "Japanese";
}

EditorLanguage editor::ParseEditorLanguage(std::string_view value) noexcept {
	return value == "English" ? EditorLanguage::English : EditorLanguage::Japanese;
}
