"""Generate original flat-shaded farm prototypes; all meshes use positive Y up."""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1] / "project/Resources/farm"


def write_mesh(name, triangles):
    lines = ["# Generated by tools/generate_farm_crop_meshes.py", "o " + name, "vt 0.5 0.5", "s off"]
    for i, (a, b, c) in enumerate(triangles):
        u = tuple(b[j] - a[j] for j in range(3))
        v = tuple(c[j] - a[j] for j in range(3))
        n = (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
        length = math.sqrt(sum(x*x for x in n))
        assert length > 1e-8
        for p in (a, b, c):
            assert all(math.isfinite(x) for x in p)
            lines.append("v " + " ".join(f"{x:.7f}" for x in p))
        lines.append("vn " + " ".join(f"{x/length:.7f}" for x in n))
        lines.append("f " + " ".join(f"{i*3+j+1}/1/{i+1}" for j in range(3)))
    ROOT.mkdir(parents=True, exist_ok=True)
    (ROOT / (name + ".obj")).write_text("\n".join(lines) + "\n", encoding="ascii")
    print(name, len(triangles), "triangles")


def root_mesh(profile, segments=12):
    rings = [[(r*math.cos(i*math.tau/segments), y, r*math.sin(i*math.tau/segments))
              for i in range(segments)] for y, r in profile]
    faces = []
    for low, high in zip(rings, rings[1:]):
        for i in range(segments):
            j = (i+1) % segments
            faces += [(low[i], high[i], high[j]), (low[i], high[j], low[j])]
    for i in range(segments):
        j = (i+1) % segments
        faces += [((0, profile[0][0], 0), rings[0][i], rings[0][j]),
                  ((0, profile[-1][0], 0), rings[-1][j], rings[-1][i])]
    return faces


def leaves_mesh():
    faces = []
    for i in range(5):
        angle = i*math.tau/5
        def point(x, y, z):
            return (x*math.cos(angle)-z*math.sin(angle), y, x*math.sin(angle)+z*math.cos(angle))
        vertices = [point(0, 0, 0), point(0.55, 0.48, -0.24), point(1, 1, 0),
                    point(0.55, 0.48, 0.24), point(0.52, 0.62, 0), point(0.52, 0.38, 0)]
        # Closed leaf volume: normals point away from its interior.
        center = tuple(sum(p[j] for p in vertices)/6 for j in range(3))
        for a,b,c in [(0,1,4),(1,2,4),(2,3,4),(3,0,4),(1,0,5),(2,1,5),(3,2,5),(0,3,5)]:
            tri = [vertices[a],vertices[b],vertices[c]]
            u = [tri[1][j]-tri[0][j] for j in range(3)]
            v = [tri[2][j]-tri[0][j] for j in range(3)]
            n = (u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])
            if sum(n[j]*(tri[0][j]-center[j]) for j in range(3)) < 0:
                tri[1],tri[2] = tri[2],tri[1]
            faces.append(tuple(tri))
    return faces


if __name__ == "__main__":
    write_mesh("crop_turnip", root_mesh([(0,.06),(.12,.62),(.42,1),(.72,.90),(1,.32)]))
    write_mesh("crop_carrot", root_mesh([(0,.035),(.45,.40),(.84,1),(1,.80)]))
    write_mesh("crop_leaves", leaves_mesh())
