"""Generate original primitive assets and an OFL glyph atlas; no sample inputs."""
from pathlib import Path
import json
import math
import random
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "project/Resources"
OUT = RES / "farm"


def mesh(name, triangles):
    lines = ["# Generated by tools/generate_farm_runtime_assets.py", "o " + name, "s off", "vt 0 0"]
    for i, (a, b, c) in enumerate(triangles):
        u = [b[j] - a[j] for j in range(3)]
        v = [c[j] - a[j] for j in range(3)]
        n = [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
        length = math.sqrt(sum(x*x for x in n))
        assert length > 1e-8
        lines.extend("v " + " ".join(f"{x:.8f}" for x in p) for p in (a, b, c))
        lines.append("vn " + " ".join(f"{x/length:.8f}" for x in n))
        lines.append("f " + " ".join(f"{i*3+j+1}/1/{i+1}" for j in range(3)))
    (OUT / (name + ".obj")).write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    Image.new("RGBA", (4, 4), "white").save(OUT / "white.png")
    for name in ("particle_circle", "particle_ring"):
        im = Image.new("RGBA", (64, 64))
        pixels = []
        for y in range(64):
            for x in range(64):
                r = math.hypot(x-31.5, y-31.5) / 31.5
                alpha = max(0, 1-r) ** 2 if name.endswith("circle") else max(0, 1-abs(r-0.65)/0.2)
                pixels.append((255, 255, 255, round(255*alpha)))
        im.putdata(pixels)
        im.save(OUT / (name + ".png"))
    for index in range(2):
        rng = random.Random(20260928 + index)
        im = Image.new("L", (128, 128))
        im.putdata([rng.randrange(256) for _ in range(128*128)])
        im.convert("RGBA").save(OUT / f"noise{index}.png")
    mesh("ground", [((-1,0,-1),(-1,0,1),(1,0,1)), ((-1,0,-1),(1,0,1),(1,0,-1))])
    # A stationary low-poly pawn, centered on the existing player collider.
    triangles = []
    rings = [(-1.0,0.30),(-0.9,0.40),(-0.75,0.40),(0.0,0.22),(0.25,0.38),(0.65,0.28)]
    segments = 12
    def point(y, radius, i):
        angle = i*math.tau/segments
        return (radius*math.cos(angle), y, radius*math.sin(angle))
    for (ya,ra),(yb,rb) in zip(rings,rings[1:]):
        for i in range(segments):
            a,b = point(ya,ra,i),point(ya,ra,i+1)
            c,d = point(yb,rb,i),point(yb,rb,i+1)
            triangles.extend([(a,c,b),(b,c,d)])
    for i in range(segments):
        triangles.append(((0,-1,0),point(-1,.3,i),point(-1,.3,i+1)))
        triangles.append((point(.65,.28,i),(0,.9,0),point(.65,.28,i+1)))
    mesh("player_marker", triangles)
    config = json.loads((RES / "ui/font/ascii_bitmap_font.json").read_text(encoding="utf-8"))
    chars = config["characters"]
    cols, w, h = config["columns"], config["glyphWidth"], config["glyphHeight"]
    atlas = Image.new("RGBA", (cols*w, math.ceil(len(chars)/cols)*h))
    font = ImageFont.truetype(str(RES / "fonts/NotoSansJP-VF.ttf"), 24)
    font.set_variation_by_axes([500])
    draw = ImageDraw.Draw(atlas)
    for i,char in enumerate(chars):
        box = font.getbbox(char, anchor="lt")
        assert box[2]-box[0] <= w-2 and box[3]-box[1] <= h-2, (char,box)
        x,y = i%cols*w, i//cols*h
        draw.text((x+2,y+26),char,font=font,fill="white",anchor="ls")
    atlas.save(ROOT / "project" / config["texture"])
    print("Generated original runtime primitives/textures and Noto glyph atlas")


if __name__ == "__main__":
    main()
